### ISSUE TITLE
Severity Flag Alert should not be sent for bug which had severity explicitly set to N/A

### ISSUE THREAD

**Issue by msujaws** [mozilla/relman-auto-nag#1001]
In https://bugzilla.mozilla.org/show_bug.cgi?id=1648107, severity was set to N/A because the feature is still disabled by default, yet I just received an email saying that " The following bug has no Severity field set for the last 4 weeks".

Can we update the query to check that a human has not set the severity to N/A?

**Comment by emceeaich** [comment]
Hi Jared,

We expect every defect to have a non-default, non-N/A value of severity.
Since a work around exists, via disabling the feature, this bug would be a
S3.

**Comment by msujaws** [comment]
Okay, thanks for the clarification. I'll update the bug.
