### ISSUE TITLE
The wrong triage owner is designated for Firefox:Sync AutoNag

### ISSUE THREAD

**Issue by lougeniaC64** [mozilla/relman-auto-nag#1007]
The triage owner field for Bugzilla bugs created for the Firefox:Sync component are not populated with the current triage owner as specified in our triage Google calender provided for AutoNag. For instance, Bug 1658691 designates me as triage owner though it was created during the week that Mark Hammond should be triage owner.

FYI: There may be some other process that needs to occur when the calendar is updated for these changes to be reflected in the triage owner field. Either way, any guidance would be greatly appreciated.

Adding [the original Bugzilla ticket](https://bugzilla.mozilla.org/show_bug.cgi?id=1658985) I created for posterity.

**Comment by calixteman** [comment]
It's something we could easily fix if Bugzilla had an api endpoint to update triage owner.
So once this feature is available I'll fix that in autonag.
