### ISSUE TITLE
look for security bugs that have landed but aren't closed

### ISSUE THREAD

**Issue by jcristau** [mozilla/relman-auto-nag#1063]
Resolving security bugs after a merge to central is a manual process so it occasionally gets missed.
It would be nice if we had some automation to flag when that happens.

Something like:
- revision landed on mozilla-central (and didn't get backed out)
- corresponding bug is restricted, still open, doesn't have `leave-open`

Not too sure yet how to do the first part of this, possibly "phab revision was closed more than N (24?) hours ago", if that's a thing?

cc @Archaeopteryx @rvandermeulen

**Comment by calixteman** [comment]
For your information, we use phab api:
https://github.com/mozilla/relman-auto-nag/blob/master/auto_nag/scripts/not_landed.py#L16
and the doc for phab:
https://phabricator.services.mozilla.com/conduit/

Using `differential.revision.search`, it's possible to check if status is `published` and check if  `dateModified` is lower than...
I don't know if it's possible to get the real closed timestamp, need to ask to glob or dkl.

**Comment by Archaeopteryx** [comment]
>     * corresponding bug is restricted, still open, doesn't have `leave-open`
Can you check if the commit is mentioned in a comment instead? When tests landed later with the same bug number, the bug has already been closed.

**Comment by jcristau** [comment]
> > ```
> > * corresponding bug is restricted, still open, doesn't have `leave-open`
> > ```
> 
> Can you check if the commit is mentioned in a comment instead? When tests landed later with the same bug number, the bug has already been closed.

I ended up doing just that, not looking at attachments / phabricator at all, and not looking at bug status.  That seems like a good enough proxy.

**Comment by jcristau** [comment]
Also I didn't restrict the check to security bugs.
