### ISSUE TITLE
Don't move bugs into components they were just moved out of

### ISSUE THREAD

**Issue by gcp** [mozilla/relman-auto-nag#1082]
https://bugzilla.mozilla.org/show_bug.cgi?id=1695772#c3

Bug was filed in Core::IPC, manually moved out of it, but then the bot moved it back.

**Comment by jcristau** [comment]
Duplicate of #877

**Comment by marco-c** [comment]
@jcristau this is a new bug, a regression from 4835f12a23e02fe66afb3bf430c23f54c10971b3.

**Comment by gcp** [comment]
More cases of this problem:
https://bugzilla.mozilla.org/show_bug.cgi?id=1696337#c4
