### ISSUE TITLE
Nag people on bugs that prevent fuzzing from making progress (fuzzblockers)

### ISSUE THREAD

**Issue by marco-c** [mozilla/relman-auto-nag#1147]
We can, for example, ask if a Pernosco session would be useful. And we should make it clear that the bug is a fuzzblocker.

**Comment by marco-c** [comment]
As part of this, we should also suggest setting severity to S2.

**Comment by suhaibmujahid** [comment]
From @pyoor in the [fuzzing room](https://matrix.to/#/#fuzzing:mozilla.org) on Matrix:
 
> A list of example bugs: https://bugzilla.mozilla.org/buglist.cgi?status_whiteboard=fuzzblocker&query_format=advanced&status_whiteboard_type=allwordssubstr&list_id=16155338&classification=Client%20Software&classification=Developer%20Infrastructure&classification=Components&classification=Server%20Software&classification=Other&resolution=---&bug_status=UNCONFIRMED&bug_status=NEW&bug_status=ASSIGNED

**Comment by suhaibmujahid** [comment]
> We can, for example, ask if a Pernosco session would be useful.

Do you mean suggesting this in a comment? (The current PR draft only sends weekly nag emails)

> And we should make it clear that the bug is a fuzzblocker.

The bugs already have the `[fuzzblocker]` whiteboard tag. Do you think we should do something more than weekly nag emails?

> As part of this, we should also suggest setting severity to S2.

I see that the `no_severity` tool already taking care of this (example [Bug 1769798#c3](https://bugzilla.mozilla.org/show_bug.cgi?id=1769798#c3)). Why do we need to handle the severity here also?

**Comment by marco-c** [comment]
> > We can, for example, ask if a Pernosco session would be useful.
> 
> Do you mean suggesting this in a comment? (The current PR draft only sends weekly nag emails)

Yes.

> 
> > And we should make it clear that the bug is a fuzzblocker.
> 
> The bugs already have the `[fuzzblocker]` whiteboard tag. Do you think we should do something more than weekly nag emails?

I was thinking, if we add a comment, to explain what "fuzzblocker" means, not everybody might be familiar with the term.

> > As part of this, we should also suggest setting severity to S2.
> 
> I see that the `no_severity` tool already taking care of this (example [Bug 1769798#c3](https://bugzilla.mozilla.org/show_bug.cgi?id=1769798#c3)). Why do we need to handle the severity here also?

no_severity is adding needinfo to ask people to set severity, in this case instead we want to ask to bump the severity if the severity is low.
