### ISSUE TITLE
Bugzilla link in [autonag] email is not correct

### ISSUE THREAD

**Issue by jensstutte** [mozilla/relman-auto-nag#1178]
There seem to appear only a limited set of components on that query (while the included table seems to be correct):

https://bugzilla.mozilla.org/query.cgi?email2=wptsync%40mozilla.bugs&emailreporter2=1&emailtype2=notequals&f1=bug_type&f10=component&f11=CP&f12=OP&f13=product&f14=component&f15=CP&f16=OP&f17=product&f18=component&f19=CP&f2=flagtypes.name&f20=OP&f21=product&f22=component&f23=CP&f24=OP&f25=product&f26=component&f27=CP&f28=OP&f3=bug_severity&f4=status_whiteboard&f5=keywords&f6=creation_ts&f7=OP&f8=OP&f9=product&j7=OR&keywords=intermittent-failure&keywords_type=nowords&list_id=15858268&o1=equals&o10=equals&o13=equals&o14=equals&o17=equals&o18=equals&o2=notsubstring&o21=equals&o22=equals&o25=equals&o26=equals&o3=anyexact&o4=notsubstring&o5=nowords&o6=greaterthan&o9=equals&query_format=advanced&resolution=---&v1=defect&v10=DOM%3A%20Content%20Processes&v13=Core&v14=DOM%3A%20File&v17=Core&v18=DOM%3A%20Push%20Notifications&v2=needinfo%3F&v21=Core&v22=DOM%3A%20Service%20Workers&v25=Core&v26=DOM%3A%20Window%20and%20Location&v3=--%2C%20n%2Fa&v4=%5Bno-nag%5D&v5=meta&v6=-1y&v9=Core
vs. 
https://bugzilla.mozilla.org/buglist.cgi?o7=equals&v5=meta&v7=jstutte%40mozilla.com&f1=bug_type&o5=nowords&o3=anyexact&emailreporter2=1&keywords_type=nowords&f6=creation_ts&keywords=intermittent-failure&f2=flagtypes.name&v3=--%2C%20n%2Fa&f4=status_whiteboard&emailtype2=notequals&v1=defect&list_id=15858227&f7=triage_owner&f5=keywords&o1=equals&query_format=advanced&classification=Client%20Software&classification=Developer%20Infrastructure&classification=Components&classification=Server%20Software&classification=Other&o6=greaterthan&email2=wptsync%40mozilla.bugs&f3=bug_severity&v4=%5Bno-nag%5D&v2=needinfo%3F&v6=-1y&resolution=---&o4=notsubstring&o2=notsubstring

(obviously the triage owner variant cannot be used here, but it should match in my case).

**Comment by calixteman** [comment]
In my dry-run I got this [url](https://bugzilla.mozilla.org/buglist.cgi?keywords=intermittent-failure&keywords_type=nowords&email2=wptsync%40mozilla.bugs&emailreporter2=1&emailtype2=notequals&resolution=---&f1=bug_type&o1=equals&v1=defect&f2=flagtypes.name&o2=notsubstring&v2=needinfo%3F&f3=bug_severity&o3=anyexact&v3=--%2C+n%2Fa&f4=status_whiteboard&o4=notsubstring&v4=%5Bno-nag%5D&f5=keywords&o5=nowords&v5=meta&f6=creation_ts&o6=greaterthan&v6=-1y&j7=OR&f7=OP&j8=AND&f8=OP&f9=product&o9=equals&v9=Core&f10=component&o10=equals&v10=DOM%3A+Content+Processes&f11=CP&j12=AND&f12=OP&f13=product&o13=equals&v13=Core&f14=component&o14=equals&v14=DOM%3A+File&f15=CP&j16=AND&f16=OP&f17=product&o17=equals&v17=Core&f18=component&o18=equals&v18=DOM%3A+Push+Notifications&f19=CP&j20=AND&f20=OP&f21=product&o21=equals&v21=Core&f22=component&o22=equals&v22=DOM%3A+Service+Workers&f23=CP&j24=AND&f24=OP&f25=product&o25=equals&v25=Core&f26=component&o26=equals&v26=DOM%3A+Window+and+Location&f27=CP&j28=AND&f28=OP&f29=product&o29=equals&v29=Core&f30=component&o30=equals&v30=DOM%3A+postMessage&f31=CP&j32=AND&f32=OP&f33=product&o33=equals&v33=Core&f34=component&o34=equals&v34=Spelling+checker&f35=CP&j36=AND&f36=OP&f37=product&o37=equals&v37=Core&f38=component&o38=equals&v38=Storage%3A+Cache+API&f39=CP&j40=AND&f40=OP&f41=product&o41=equals&v41=Core&f42=component&o42=equals&v42=Storage%3A+IndexedDB&f43=CP&j44=AND&f44=OP&f45=product&o45=equals&v45=Core&f46=component&o46=equals&v46=Storage%3A+Quota+Manager&f47=CP&j48=AND&f48=OP&f49=product&o49=equals&v49=Core&f50=component&o50=equals&v50=Storage%3A+localStorage+%26+sessionStorage&f51=CP&f52=CP) and I noticed that double quotes are missing around the url so it's maybe related to the issue you met.
Here's a PR: https://github.com/mozilla/relman-auto-nag/pull/1181 to fix the dquotes issue.

**Comment by jensstutte** [comment]
FWIW, it is wrapped after 999 characters. Looks like some fixed buffer of 1000 somewhere?

**Comment by jensstutte** [comment]
OK, this seems to be the email protocol itself?

2.1.1.  Line Length Limits

   There are two limits that this specification places on the number of
   characters in a line.  Each line of characters MUST be no more than
   998 characters, and SHOULD be no more than 78 characters, excluding
   the CRLF.

Can we have some tinyurl here?
