### ISSUE TITLE
Propose to increase severity for bugs S4/S5 with several duplicates/see also/CC/votes/comments from unique users

### ISSUE THREAD

**Issue by pascalchevrel** [mozilla/relman-auto-nag#1184]
When a bug has several duplicates, it indicates that the issue is severe enough to push users to report it to us. Those bugs should probably not have a S4 or S5 severity.

Example: https://bugzilla.mozilla.org/show_bug.cgi?id=1652307

It would be nice to needinfo the assignee or the triage owner and ask if the priority should be higher.

**Comment by sylvestre** [comment]
Same for "See also"
Example:
https://bugzilla.mozilla.org/show_bug.cgi?id=1743954

**Comment by marco-c** [comment]
Good idea, we have that frequently with webcompat issues or pdf.js issues (split between bugzilla and github).

**Comment by marco-c** [comment]
We were discussing about this and how to best handle cases where the bot proposes an increase, the developers ignore it or set it to a low severity (like S3), and then later we get more duplicates.

@calixteman said:
> A possibility is to add the number of dup in the comment made by the bot, and if at some point prev_dup_num +whatever >= current_num then nag again or nag when num of bugs is a multiple of 3 or whatever
> we can have different strategies based on the number of dups
> 3 => reset, 6 => reset + tracking request, ... something like that

**Comment by marco-c** [comment]
We can also use #1280 for this.

**Comment by suhaibmujahid** [comment]
@marco-c I think that the number of *comments from unique users* is highly correlated with the number of CC. Unless the user opts out, they will be added to the CC list by default. 

We could still consider the number of comments; it can still be an indicator of abnormal activity.

What do you think?

**Comment by suhaibmujahid** [comment]
Both of [Firfox's Defect Severity](https://firefox-source-docs.mozilla.org/bug-mgmt/guides/severity.html) page and [Bugzilla Field Descriptions](https://wiki.mozilla.org/BMO/UserGuide/BugFields) wiki page show that the enumerated severity values range up to `S4`. Should we anticipate an `S5` severity?

**Comment by marco-c** [comment]
> @marco-c I guess that the number of _comments from unique users_ is highly correlated with the number of CC. Unless the user opts out, they will be added to the CC list by default.
> 
> We could still consider the number of comments; it can still indicate abnormal activities.
> 
> What do you think?

That's true, in most cases they should be highly correlated. I'd say let's leave it out, it's simpler to deal with fewer thresholds.

**Comment by marco-c** [comment]
> Both of [Firfox's Defect Severity](https://firefox-source-docs.mozilla.org/bug-mgmt/guides/severity.html) page and [Bugzilla Field Descriptions](https://wiki.mozilla.org/BMO/UserGuide/BugFields) wiki page show that the enumerated severity values range up to `S4`. Should we anticipate an `S5` severity?

Funny I hadn't noticed the issue title was mentioning S4 and S5, my eyes were reading S3 and S4. I guess S3 and S4 is actually what @pascalchevrel meant here.
