### ISSUE TITLE
Error closing a bug as spam

### ISSUE THREAD

**Issue by marco-c** [mozilla/relman-auto-nag#1222]
> 2021-11-12 07:17:05,017 - ERROR - spambug: Cannot put data for bug 1740865 (change => {'comment': {'body': 'The [Bugbug](https://github.com/mozilla/bugbug/) bot thinks this bug is invalid.\nIf you think the bot is wrong, please reopen the bug and move it back to its prior component.\n\nPlease note that this is a production bug database used by the Mozilla community to develop Firefox, Thunderbird and other products.\nFiling test bugs here will waste the time of our contributors, volunteers and employees.\nIf you continue to abuse bugzilla.mozilla.org, your account will be disabled.'}, 'product': 'Invalid Bugs', 'component': 'General', 'version': 'unspecified', 'milestone': '---', 'status': 'RESOLVED', 'resolution': 'INVALID'}).

Maybe because of the tracking flags?

I closed that bug manually for now.

**Comment by calixteman** [comment]
If it's possible we can try to debug on https://bugzilla.allizom.org/home but iirc bugzilla on allizom is not exactly the same as the bugzilla in mozilla.org...

**Comment by marco-c** [comment]
Duplicate of #1438.
