### ISSUE TITLE
Blocklist Mach/Build components from "severity unset" check

### ISSUE THREAD

**Issue by mitchhentges** [mozilla/relman-auto-nag#1248]
The components I'd like blocklisted are:
* Firefox Build System :: Bootstrap Configuration
* Firefox Build System :: General
* Firefox Build System :: General: Unsupported Platforms
* Firefox Build System :: Mach Core
* mozilla.org :: MozillaBuild

My team manages these components, and we just use the "priority" field without "severity" :)

**Comment by globau** [comment]
We're using severity now.
