### ISSUE TITLE
Don't autonag claiming bugs "haven't had a severity set for 4 weeks" if they have moved component/product in that timeframe

### ISSUE THREAD

**Issue by gijsk** [mozilla/relman-auto-nag#1250]
People shouldn't be held responsible for the triage of bugs that they had no opportunity to see, given that until recently they weren't in their bailiwick.

**Comment by marco-c** [comment]
This should already be the case. Do you have a specific example where it failed?

**Comment by gijsk** [comment]
<html><head></head><body><p>
  The following bug has no Severity field set for the last 4 weeks:
</p>


Component | Bug | Summary
-- | -- | --
Toolbars and Customization | 1742248 | Stop/reload button flashes extremely rapidly on sites with iframes

This is the email I got today:

<p>See the query on <a href="https://bugzilla.mozilla.org/buglist.cgi?keywords=intermittent-failure&amp;keywords_type=nowords&amp;email2=wptsync%40mozilla.bugs&amp;emailreporter2=1&amp;emailtype2=notequals&amp;resolution=---&amp;f21=bug_type&amp;o21=equals&amp;v21=defect&amp;f22=flagtypes.name&amp;o22=notsubstring&amp;v22=needinfo%3F&amp;f23=bug_severity&amp;o23=anyexact&amp;v23=--%2C+n%2Fa&amp;j2=OR&amp;f2=OP&amp;j3=AND&amp;f3=OP&amp;f4=product&amp;o4=changedbefore&amp;v4=-28d&amp;n5=1&amp;f5=product&amp;o5=changedafter&amp;v5=-28d&amp;f6=CP&amp;j7=AND&amp;f7=OP&amp;f8=component&amp;o8=changedbefore&amp;v8=-28d&amp;n9=1&amp;f9=component&amp;o9=changedafter&amp;v9=-28d&amp;f10
> =CP&amp;j11=AND&amp;f11=OP&amp;f12=creation_ts&amp;o12=lessthaneq&amp;v12=-28d&amp;n13=1&amp;f13=product&amp;o13=everchanged&amp;n14=1&amp;f14=component&amp;o14=everchanged&amp;f15=CP&amp;f16=CP&amp;f24=status_whiteboard&amp;o24=notsubstring&amp;v24=%5Bno-nag%5D&amp;f25=keywords&amp;o25=nowords&amp;v25=meta&amp;f26=creation_ts&amp;o26=greaterthan&amp;v26=-1y&amp;j27=OR&amp;f27=OP&amp;j28=AND&amp;f28=OP&amp;f29=product&amp;o29=equals&amp;v29=Firefox&amp;f30=component&amp;o30=equals&amp;v30=File+Handling&amp;f31=CP&amp;j32=AND&amp;f32=OP&amp;f33=product&amp;o33=equals&amp;v33=Firefox&amp;f34=component&amp;o34=equals&amp;v34=Toolbars+and+Customization&amp;f35=CP&amp;f36=CP">Bugzilla</a>.</p></body></html>
