### ISSUE TITLE
Soften autonag message detecting spam bugs and suggest translation for bug descriptions written in languages other than English

### ISSUE THREAD

**Issue by dholbert** [mozilla/relman-auto-nag#1277]
I just ran across https://bugzilla.mozilla.org/show_bug.cgi?id=1730091#c0 where it seems the bug-reporter submitted their description in Japanese, and [bugbug closed the bug as invalid with a stern warning for the user](https://bugzilla.mozilla.org/show_bug.cgi?id=1730091#c1).  Bugbug's warning ends with this rather-severe admonishment: **"If you continue to abuse bugzilla.mozilla.org your account will be disabled."**

I assume bugbug has some "gibberish detection system" which thought that the Japanese text here was gibberish and hence abuse, or something to that effect.

A few thoughts about what could have gone better there:
(1) Maybe bugbug needs a way to detect foreign-language text which deactivates its gibberish-detection-system? (if it has such a system)

(2) Maybe bugbug's gibberish/abuse-response-blurb should encourage folks to ensure that their bugs are reported in English (and suggest Google Translate or similar), so that they have a hint about why their post may have been classified as abuse.

(3) Maybe the final admonishment should be softened or reworded so as not to imply that the user *has already been judged to have abused bugzilla* (which in fact they had not, in this case)?

**Comment by marco-c** [comment]
I guess we could build automatic detection of foreign language text, but it might be more complex than it is worth given that this is not so frequent.

I think we should just change the message to mention something like "If your bug description is written in a non-English language, please use Google Translate or a similar service to translate it.".

Wdyt @globau?

**Comment by dholbert** [comment]
Sure -- that additional sentence (combined with a softening of the final sentence to not-imply-that-we-know-for-sure-that-the-message-is-abuse) sounds like a good improvement to me.

Thanks!

**Comment by globau** [comment]
> I think we should just change the message to mention something like "If your bug description is written in a non-English language, please use Google Translate or a similar service to translate it.".

+1

> "If you continue to abuse bugzilla.mozilla.org your account will be disabled."

How about "Accounts that abuse bugzilla.mozilla.org will be disabled."  ?

**Comment by dholbert** [comment]
Sounds good to me - thanks!
