### ISSUE TITLE
Some auto-nag rules expect non-numeric severity values

### ISSUE THREAD

**Issue by suhaibmujahid** [mozilla/relman-auto-nag#1319]
Examples:

https://github.com/mozilla/relman-auto-nag/blob/00b3f7cb029f434728c293539d2015d1dbd29855/auto_nag/scripts/topcrash_bad_severity.py#L18

https://github.com/mozilla/relman-auto-nag/blob/e8172bf302eda9dd3e0d6e13379408ca404237a1/auto_nag/scripts/tracked_bad_severity.py#L25

https://github.com/mozilla/relman-auto-nag/blob/e8172bf302eda9dd3e0d6e13379408ca404237a1/auto_nag/scripts/tracked_bad_severity.py#L62

https://github.com/mozilla/relman-auto-nag/blob/ba257a41b4ab271f8e12273dcc4ec491a7465bb4/auto_nag/tests/test_bzcleaner.py#L64

https://github.com/mozilla/relman-auto-nag/blob/2e1372cc7cb8336ff15a45fd0eafb920abbc19e9/auto_nag/history.py#L309

**Comment by marco-c** [comment]
Good find, we should update these with the new severity values (we used to have "major", "normal", "minor", etc., but now we have S1, S2, S3, S4).

**Comment by suhaibmujahid** [comment]
@marco-c: Are the keywords `sec-critical` and `sec-high` still in use or is replaced with enumerated ones?

Example:
https://github.com/mozilla/relman-auto-nag/blob/0d9e6bea33ea30d69c5769cf444bb87700f91edf/auto_nag/scripts/survey_sec_bugs.py#L32-L35

**Comment by marco-c** [comment]
Yes, the security keywords didn't change.
