### ISSUE TITLE
assignee_no_login: some bugs aren't correctly updated

### ISSUE THREAD

**Issue by calixteman** [mozilla/relman-auto-nag#1335]
For any reasons in the last days I always see in the emails:
![image](https://user-images.githubusercontent.com/5641725/159007357-cd144214-646e-45c3-bbfc-1650697d7b75.png)
and no change in the bug themselves.
So likely we don't manage to update the bugs (or something is wrong on the bz's side) and consequently we see them every day.

**Comment by marco-c** [comment]
We discussed this on Matrix: Benjamin blocked needinfo requests and Emily's account is disabled.
#1231 will take care of the problem with Emily, while Benjamin will be needinfoed when he's back.
