### ISSUE TITLE
Propose increasing severity for sec-high/sec-critical bugs that are lower than S2

### ISSUE THREAD

**Issue by marco-c** [mozilla/relman-auto-nag#1336]

**Comment by suhaibmujahid** [comment]
This may fit as a part of the [severity_underestimated](https://github.com/mozilla/relman-auto-nag/blob/63a9db6109b84c44a20f3f5baebe609548b9d6ba/auto_nag/scripts/severity_underestimated.py) tool.

@marco-c wdyt?

**Comment by marco-c** [comment]
@suhaibmujahid that would work, though the query might become too complex? Maybe better to have a separate script like the accessibility one, so the queries can be much simpler.
Another option would be to run multiple separate queries as part of the same script.

**Comment by suhaibmujahid** [comment]
I query the keywords, it seems that all bugs with `sec-high` and `sec-critical` keywords are resolved ([0 bugs open](https://bugzilla.mozilla.org/buglist.cgi?keywords=sec-high%2Csec-critical&keywords_type=anywords&resolution=---), [4056 bugs closed](https://bugzilla.mozilla.org/buglist.cgi?keywords=sec-high%2Csec-critical&keywords_type=anywords&list_id=16026922&query_format=advanced&order=priority%2Cbug_severity&limit=0)).

Based on this, it seems that the script will not have an impact on current bugs.  

@marco-c do I miss something?

**Comment by marco-c** [comment]
@suhaibmujahid sec-high and sec-critical are only visible if you have security permissions, there are actually some that are not S2.
