### ISSUE TITLE
Cancel review requests on inactive reviewers

### ISSUE THREAD

**Issue by marco-c** [mozilla/relman-auto-nag#1382]
If canceling them is hard, we can also just needinfo the triage owner on the bugs associated to the revisions with inactive reviewers.

**Comment by suhaibmujahid** [comment]
We could needinfo a possible alternative reviewer to takeover. The alternative reviewer could take care of cancelling the review requests on the inactive reviewer.

The alternative reviewer could be identified based on the history using simple rules or an ML model. If we could not identify an alternative reviewer based on the history, we could fallback to the team manager or triage owner.

**Comment by marco-c** [comment]
We can use the module system @zzzeid is working on to identify an alternative reviewer (sharing the implementation details with moz-phab's reviewer suggestion, https://bugzilla.mozilla.org/show_bug.cgi?id=1773291).

For the time being, until we have the possibility of identifying alternative reviewers, we could just cancel the review automatically and needinfo the author of the patch to ask them to find another reviewer.

**Comment by suhaibmujahid** [comment]
> needinfo the author of the patch to ask them to find another reviewer.

I think if the patch author themself is not active, we should not consider the bug.

**Comment by suhaibmujahid** [comment]
If the revision has a "Group Reviewers" assutated with, I do not think we need to notify about inactive reviewer, even if the reviewer mentioned explicitly alongside the group reviewer.

Examples:
- https://phabricator.services.mozilla.com/D131738
- https://phabricator.services.mozilla.com/D151106

**Comment by marco-c** [comment]
It might still be valuable if the single reviewer is set as "blocking", which means the author would have to wait on their approval before being able to land the revision.
