### ISSUE TITLE
Add needinfos for bugs that are Performance: P1

### ISSUE THREAD

**Issue by julienw** [mozilla/relman-auto-nag#1389]
The Performance flag is something that was added recently to Bugzilla, and can have a few values: P1, P2, P3, ?, - and ---.

It would be good that the nagging bot automatically adds need info for the unassigned open Performance: P1 bugs. There isn't a lot of them, see https://mozilla.pettay.fi/performance.html, so I don't think folks would complain too loud :-)

I wonder if other things you're already doing for other types of bug could help us here. For example flagging Performance: P1 bugs with no update for XXX days, is that something you do for other bugs? I'd be happy to tap into some of the things you're already doing :-)

Thanks!

**Comment by julienw** [comment]
Hey,
I discussed this with the rest of the team, and we felt this may be too agressive for now. Can we hold off on doing this for now?
Thanks

**Comment by julienw** [comment]
Yeah, @smaug---- is working on this, I believe you got in touch already :-)

**Comment by smaug----** [comment]
The weekly email shouldn't have just P1, but the content would be close to https://mozilla.pettay.fi/performance.html (looks like that link was already in the initial comment).
I need to now figure out how to convert that to a weekly email to dev-platform. The page itself is just doing couple of simple bugzilla queries, and hopefully similar things can be done perhaps using autonag.

**Comment by marco-c** [comment]
We can definitely do that with autonag. Usually we send list of bugs to teams, why are you thinking of sending it to dev-platform instead?

The other option is to add the list to the quality notification (example https://docs.google.com/document/d/1D51BStT_r2qjzjabzOjSGYe9BjvDj-S-rEEp2JJQxN8/edit).

**Comment by smaug----** [comment]
Why would we send to MoCo internal teams when this is about software components in the project? (and nothing here has any privacy or security related concerns).
And I don't get any team specific autonag emails (or perhaps some triage email?). Do they go to the managers only? This email should go to all the devs.

**Comment by marco-c** [comment]
> Why would we send to MoCo internal teams when this is about software components in the project? (and nothing here has any privacy or security related concerns).

The quality notification is a way to surface important issues to teams. It is sent to managers of teams, but can easily be sent to other people too (e.g. people belonging to the team). A "team" in Bugzilla terms is just a set of components (e.g. https://bugzilla.mozilla.org/rest/config/component_teams/DOM%20LWS). 

> And I don't get any team specific autonag emails (or perhaps some triage email?). Do they go to the managers only? This email should go to all the devs.

Yeah, there are actually no team specific autonag emails at the moment, the triage emails are sent to triage owners and managers of the teams. We can easily send the email to all devs of a team though. The team is just a set of components with a manager linked to it, so we can either use the granularity of the component (and send an email to each triage owner) or use the granularity of the team (and send an email to all people belonging to a given team).

> I could still add, that since the email is about raising the awareness of performance, the information about it should go the the folks who are actually going to fix the issues. That will hopefully improve the overall culture of performance.

The goal of the quality notification is to raise awareness about important issues to teams about their components, so it looks like a good place to also list important performance bugs. It goes to managers by default, but it can easily be adjusted to be sent to individual engineers too.
Given that it is a report to raise awareness about important issues, I think adding performance bugs makes sense as they'd automatically get importance by being in the report.

**Comment by julienw** [comment]
We decided to close this issue for now. Olli's work is slightly related but not directly, and we'll follow this in another place. Thanks Marco!
