### ISSUE TITLE
[patch_closed_bug] Do not warn on backports

### ISSUE THREAD

**Issue by suhaibmujahid** [mozilla/relman-auto-nag#1409]
> @marco-c:
> we shouldn't warn in cases like https://bugzilla.mozilla.org/show_bug.cgi?id=1762125#c55
> where the additional patch is just a backport

**Comment by marco-c** [comment]
We simply have to exclude patches that have "approval-mozilla-*" flags. To give time to people to set the flags, we can warn a couple hours after the patch is attached.
