### ISSUE TITLE
[tracked_needinfo] Incorrectly mark people as with no manager

### ISSUE THREAD

**Issue by suhaibmujahid** [mozilla/relman-auto-nag#1411]
@marco-c mentioned incorrect behaviour in the following email: 
> [autonag] Bugs which are tracked or nominated for tracking with needinfo? in beta for the 2022-04-07

The report marks an employee who has a manager as with no manager. In another email, the same person is not listed as with no manager.

## Root cause

https://github.com/mozilla/relman-auto-nag/blob/ba257a41b4ab271f8e12273dcc4ec491a7465bb4/auto_nag/scripts/tracked_needinfo.py#L56-L61

Flipping the `has_manager` to `True` depends on entering the loop in the first place. However, in L57 we retrieve only needinfos that are requested before `>= 1 day`. Thus, in the case of having same-day needinfos only, the script will not enter the loop and `has_manager` will stay `False`.

Thus, any bug that has needinfos that requested on the same day when the script runs (with no older needinfos), will be marked as with no manager.

**Comment by suhaibmujahid** [comment]
From Marco's email about the bug:

> @calixteman, do you remember the reason behind the 1 day choice?

**Comment by calixteman** [comment]
iirc it's to let the time to people to answer to the ni, does it make sense to you ?
