### ISSUE TITLE
Consolidate multiple bot changes into a single change for regression bugs

### ISSUE THREAD

**Issue by Standard8** [mozilla/relman-auto-nag#1415]
If you file a bug that's regressed by another bug but don't correctly fill in all the fields, you then get at least three separate updates from the release management bot.

For example, bug 1766234 just got multiple updates:

* Release status flags
* Needinfo of author
* Regression range set

This is causing more visual noise and unnecessary email spam spread over a longer period. Please could we consider somehow consolidating these changes into one?

**Comment by marco-c** [comment]
With #1419, we'll at least consolidate the three into two.

**Comment by marco-c** [comment]
We are no longer setting the "Has Regression Range" field (actually, we have decided to drop it completely), so this is already better than it was.

We should now consolidate the rest of the changes (if "regressed by" is set, we should at the same time set "regression" keyword if missing, needinfo regression author, and set status flags).
