### ISSUE TITLE
Run the uplift_beta job daily

### ISSUE THREAD

**Issue by rvandermeulen** [mozilla/relman-auto-nag#1427]
Currently, the uplift_beta job to prompt patch authors for uplift requests sometimes runs on days that don't align well with our release cycle. I don't see much downside to running it daily, however. Can we just do that unless I'm missing something?

**Comment by marco-c** [comment]
We are running it daily, but the tool is excluding bugs that were resolved within the last two days (https://github.com/mozilla/relman-auto-nag/blob/ec327387d31eb84a22b45ef96ac7dd93977de503/auto_nag/scripts/uplift_beta.py#L97-L99) to give time to bake in Nightly.
Do you think we should reduce the "bake time" to 1 day or even less?
