### ISSUE TITLE
Should NI on inactive user be redirected if author == triage-owner?

### ISSUE THREAD

**Issue by leplatrem** [mozilla/relman-auto-nag#1448]
<img width="564" alt="Screenshot 2022-05-25 at 15 50 28" src="https://user-images.githubusercontent.com/546692/170278346-a418e59b-4f71-4cd6-b95d-0076d53a822c.png">

If the author of the needinfo is the triage owner, it does not seem relevant to redirect it, does it?

**Comment by marco-c** [comment]
The reasoning is that we want to let you know if a bug is waiting for information from somebody who is no longer active, this way you can find another way to get the information or close the bug as INCOMPLETE if there is no other way to find the information that you need.

**Comment by suhaibmujahid** [comment]
> @leplatrem do you have a link to the bug?

https://bugzilla.mozilla.org/show_bug.cgi?id=1617971#c19

**Comment by marco-c** [comment]
OK, Eugen left Mozilla, so the action from the bot was useful.

@leplatrem, is the better comment (`could you find another way to get the information or close the bug as INCOMPLETE if it is not actionable?`) enough to consider this issue fixed for you? Or would you prefer something else?

**Comment by leplatrem** [comment]
I understand the reasoning now, thank you.
