### ISSUE TITLE
Ignore "Not a regression" in the regression detection

### ISSUE THREAD

**Issue by sylvestre** [mozilla/relman-auto-nag#145]
Examples:
https://bugzilla.mozilla.org/show_bug.cgi?id=1458470
https://bugzilla.mozilla.org/show_bug.cgi?id=1458471

**Comment by sylvestre** [comment]
And
"not a recent regression"
https://bugzilla.mozilla.org/show_bug.cgi?id=1459165 
https://bugzilla.mozilla.org/show_bug.cgi?id=1458885

**Comment by marco-c** [comment]
This should no longer be a problem now.
