### ISSUE TITLE
Failures in tools contractors due to missy versions

### ISSUE THREAD

**Issue by suhaibmujahid** [mozilla/relman-auto-nag#1453]
In some situations the `init_versions()` function doe not work for different reasons:

https://github.com/mozilla/relman-auto-nag/blob/0103bd251962b25a27de0bcd69d1569bd5a366fc/auto_nag/utils.py#L521-L527

This will cause many tools to have a broken contractor:

https://github.com/mozilla/relman-auto-nag/blob/0103bd251962b25a27de0bcd69d1569bd5a366fc/auto_nag/scripts/severity_tracked.py#L12-L16

https://github.com/mozilla/relman-auto-nag/blob/0103bd251962b25a27de0bcd69d1569bd5a366fc/auto_nag/scripts/telemetry_expiry_tracking_autoapproval.py#L8-L13

As a consequence, such tools will fail and break the CI (e.g. [tasks/Dy_MpwFTTGeBFeTFdpAt8Q](https://community-tc.services.mozilla.com/tasks/Dy_MpwFTTGeBFeTFdpAt8Q/runs/0/logs/public/logs/live.log#L162)):
```
======================================================================
ERROR: test_get_bz_params (auto_nag.tests.test_bzcleaner.TestBZClearnerClass)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/relman-auto-nag/auto_nag/tests/test_bzcleaner.py", line 61, in test_get_bz_params
    p = tool.get_bz_params(None)
  File "/relman-auto-nag/auto_nag/scripts/severity_tracked.py", line 69, in get_bz_params
    ] + list(self.flags_map.keys())
AttributeError: 'SeverityTracked' object has no attribute 'flags_map'
```

## Possible solutions
 - Skip running the tool in such cases (without throwing an error). 
 - Throwing an error in the contractor to be more explicit and avoid breaking the CI.

**Comment by marco-c** [comment]
Let's start with throwing an error, which is better than the current situation because at least it's explicit, and we can re-evaluate it later.
