### ISSUE TITLE
In case of regression ranges with few bugs, needinfo all authors

### ISSUE THREAD

**Issue by marco-c** [mozilla/relman-auto-nag#1475]
Currently we limit to 1, but we should be needinfoing if we have only few authors (e.g. up to 3), just like we do for performance regressions.

https://github.com/mozilla/relman-auto-nag/blob/master/auto_nag/scripts/fuzzing_bisection_without_regressed_by.py

**Comment by suhaibmujahid** [comment]
As suggested in #1465, we could start by avoiding needinfo inactive users here.
