### ISSUE TITLE
Shouldn't nag for "Failed to bisect testcase"

### ISSUE THREAD

**Issue by amccreight** [mozilla/relman-auto-nag#1477]
In [this comment](https://bugzilla.mozilla.org/show_bug.cgi?id=1744525#c39), fuzzing_bisection_without_regressed_by.py put up a needinfo for a regression range because there's a bugmon regression analysis comment (comment 3). However, the bugmon result was "Failed to bisect testcase (Testcase reproduces on start build!)". This isn't super common, but it would be good if the script recognized this case and didn't needinfo for it.

**Comment by amccreight** [comment]
I guess this could actually just be a general issue with the bot, as I came across another case where there was no [bugmon comment at all and it still did the nag](https://bugzilla.mozilla.org/show_bug.cgi?id=1740797#c23).

**Comment by marco-c** [comment]
Sorry for the noise, stupid indentation bug. Fixed by #1477.
