### ISSUE TITLE
For fuzzing bisection regressed-by needinfo-nag, don't nag if the bisection range says "Failed to bisect testcase (Testcase reproduces on start build!)"

### ISSUE THREAD

**Issue by dholbert** [mozilla/relman-auto-nag#1479]
Sometimes bugmon (the fuzzing team's bisection bot) discovers that a bug reproduces on the oldest build, i.e. it's not a regression or not a recent-enough-one to be bisectable.

When that happens, it's not helpful for the autonag bot to needinfo the bug assignee to identify a cause of the regression from the (nonexistent) bisection range.

This happened on https://bugzilla.mozilla.org/show_bug.cgi?id=1723249#c15 for example; could we update the autonag bot to avoid doing this?

**Comment by dholbert** [comment]
So essentially, we do want to nag when we see a comment from bugmon like this:
https://bugzilla.mozilla.org/show_bug.cgi?id=1683535#c6

But we don't want to nag when we see a comment from bugmon like this:
https://bugzilla.mozilla.org/show_bug.cgi?id=1723249#c2

(Maybe bugmon could be adjusted to flag such bugs with an additional bit of info in the whiteboard field? I'm not sure if that would make this easier -- e.g. if autonag bot is checking for `bugmon:bisected` in the whiteboard field, then maybe it could exclude bugs with some additional tag like `affects-start-build` in the `bugmon:...` bracketed whiteboard text, if bugmon started adding that.)

**Comment by suhaibmujahid** [comment]
Thank you @dholbert for reporting this, and sorry for any inconvenience. This was caused by a regression in the bot. Fixed by #1476.

**Comment by dholbert** [comment]
Thanks!
