### ISSUE TITLE
Also warn for bugs without the regression keyword but has "Has Regression Range=yes"

### ISSUE THREAD

**Issue by sylvestre** [mozilla/relman-auto-nag#148]
Seems that it is pretty common:
https://mzl.la/2KN89EH

**Comment by marco-c** [comment]
Maybe in these cases we should actually add "regression"? It seems we can't be wrong if we do it.

**Comment by sylvestre** [comment]
@marco-c not sure, see https://bugzilla.mozilla.org/show_bug.cgi?id=1461027
https://bugzilla.mozilla.org/show_bug.cgi?id=1461034

**Comment by marco-c** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1461027 is a regression, see comment 4 and 5.
https://bugzilla.mozilla.org/show_bug.cgi?id=1461034 might be a regression too, see comment 2.

**Comment by sylvestre** [comment]
Sure, it is a crash, it should a be a regression anyway.
I just meant that we don't have a regression range in these bugs.
