### ISSUE TITLE
inactive_ni_pending.py treats bot activity as activity

### ISSUE THREAD

**Issue by amccreight** [mozilla/relman-auto-nag#1483]
The "recent" activity in [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1505360) is:
1. In 2018, a person changed the summary and assigned the bug to somebody.
2. In 2019, a bot needinfo'd the assignee.
3. Today, a bot cleared the assignee due to inactivity.
4. Then, a bot redirected the needinfo to the triage owner "since the bug has recent activity".

In other words, no human has interacted with this bug for around 4 years. It would be better if there was some kind of double check that the recent activity was not purely from bots.

**Comment by marco-c** [comment]
We have thought about this, but there is no easy way to exclude bot activity. We can load the bug's history and parse it, but it's quite slow.
I think we can re-evaluate the choice though, given it has happened a few times and is painful to see :)
