### ISSUE TITLE
Convert `critical`, `major` and `blocker` to the new severity style

### ISSUE THREAD

**Issue by suhaibmujahid** [mozilla/relman-auto-nag#1484]
At some point we should really convert "critical" and "major" to the new style severities for these important bugs!

_Originally posted by @marco-c in https://github.com/mozilla/relman-auto-nag/pull/1451#discussion_r895526431_

**Comment by marco-c** [comment]
For <major and crashes with >=major, we have https://bugzilla.mozilla.org/show_bug.cgi?id=1789259.
For >=major, we can implement this here. In batches of 10 bugs, we can remove severity and remove the "triaged" keyword if it is set (this way we can implement the "triaged" change in parallel).
