### ISSUE TITLE
Round robin should also update triage owner on Bugzilla

### ISSUE THREAD

**Issue by marco-c** [mozilla/relman-auto-nag#1491]
This way the triage owner rotation is reflected in Bugzilla too

**Comment by suhaibmujahid** [comment]
I think this is blocked by https://bugzilla.mozilla.org/show_bug.cgi?id=1773137

**Comment by suhaibmujahid** [comment]
Waiting for https://github.com/mozilla-bteam/bmo/pull/1866 to be merged and deployed
