### ISSUE TITLE
Inactive reviewers nag incorrectly nagged for a patch with two active reviewers who had both resigned.

### ISSUE THREAD

**Issue by Standard8** [mozilla/relman-auto-nag#1553]
This nag just appeared:

https://bugzilla.mozilla.org/show_bug.cgi?id=301888#c95

For this patch:

https://phabricator.services.mozilla.com/D44078

Neither :Flod or myself are inactive, though we have both resigned from review because the patch isn't something we would accept in-product.

There should be no nag in this case.

**Comment by marco-c** [comment]
The idea was that in such cases the revision should be abandoned.

**Comment by suhaibmujahid** [comment]
Thank you for reporting this, @Standard8!

> Neither :Flod or myself are inactive, though we have both resigned from review because the patch isn't something we would accept in-product.

I'm curious why the patch was not rejected in this case since it isn't something you see it would be accepted in the product.



> Maybe the text could be altered for that case? Use something like "The following patch is waiting for review but all reviewers have resigned:",

Yes, we will clarify the first line of the message to mention resigned (not only inactive). 

> and maybe make it clearer that it possibly should be abandoned?

We already have that: "could you please find another reviewer or <ins>abandon the patch if it is no longer relevant</ins>?"

**Comment by Standard8** [comment]
> Thank you for reporting this, @Standard8!
> 
> > Neither :Flod or myself are inactive, though we have both resigned from review because the patch isn't something we would accept in-product.
> 
> I'm curious why the patch was not rejected in this case since it isn't something you see it would be accepted in the product.

I don't think we have a clear way of indicating this in phabricator, but I've generally understood rejection as "you can resubmit this with an updated patch and we'll look at it again" - which lines up with the "Needs changes" state in phab.

Here, we've used resign to indicate "sorry, this isn't the right approach and not something we would accept, I'm not interested in reviewing it again".

> > and maybe make it clearer that it possibly should be abandoned?
> 
> We already have that: "could you please find another reviewer or abandon the patch if it is no longer relevant?"

I was thinking of maybe putting the emphasis on abandon first since finding another reviewer might not be appropriate.
