### ISSUE TITLE
[triage_owner_rotations] Inconsistency with round-robin

### ISSUE THREAD

**Issue by suhaibmujahid** [mozilla/relman-auto-nag#1562]
In the `triage_owner_rotations` tool we used the calendar directly instead of using the round robin method `get`. This couses  the following inconsistency in the behaviour compared to what `RoundRobin.get()` produces:

1. When the calendar has nobody specified, we are not selecting the fallback person, instead keeping the current trigger as is.
1. When there is more than one person on the calendar, we select the first one, where `RoundRobin.get()` randomly select one of them: https://github.com/mozilla/relman-auto-nag/blob/83939641a8decf171ef3347bdd4b3fb6f75127e4/auto_nag/round_robin.py#L193-L194

The problem with the inconsistency is that some tools use the `RoundRobin` class directly, so the nags will be sent to a person different than the one on Bugzilla (not consistent with the new proposal).

I think maybe we should select the fallback in the `triage_owner_rotations` tool.  Where for the second point, I think we should avoid the random selection in `RoundRobin.get()`. With this, we can use `RoundRobin.get()` and have consistent behaviour.

At some point maybe we should drop using `RoundRobin` directly and depend on Bugzilla.

@marco-c wdyt?

**Comment by marco-c** [comment]
Yeah, I agree.
I guess RoundRobin was randomly selecting to spread the load, but perhaps it doesn't matter anymore if we rely on the calendars and the teams set the calendars up in the right way.
