### ISSUE TITLE
"The bug assignee didn't login in Bugzilla in the last months" message doesn't sound right

### ISSUE THREAD

**Issue by arai-a** [mozilla/relman-auto-nag#1566]
https://bugzilla.mozilla.org/show_bug.cgi?id=1769830#c9
> The bug assignee didn't login in Bugzilla in the last months and this bug has severity 'S2'.

The assignee's last activity is from today (2022-07-25 17:02:47 JST).
What actual data does the bot use?
If it's looking the last comment, can the message be rephrased to make it clearer?

**Comment by dholbert** [comment]
Looks like there was a known issue that's being rolled back / cleaned up, per https://bugzilla.mozilla.org/show_bug.cgi?id=1776206#c12 -- @suhaibmujahid said there "there was a problem with the detection of inactive users" and has been doing some bugzilla cleanup (restoring some needinfo's / assignees as in that bug and https://bugzilla.mozilla.org/show_bug.cgi?id=1781041#c1 ).

**Comment by marco-c** [comment]
Exactly, this was a bug in the bot that has been fixed. Suhaib has been cleaning up bad actions from the bot (we stopped it early fortunately... so a lot of bugs to cleanup but not thousands like it could have been!).
