### ISSUE TITLE
Don't set status flags on regressions to `affected` if it was `wontfix` or `disabled`

### ISSUE THREAD

**Issue by suhaibmujahid** [mozilla/relman-auto-nag#1576]
E.g. in a case like https://bugzilla.mozilla.org/show_bug.cgi?id=1781724#c7

Reported by @rvandermeulen

**Comment by suhaibmujahid** [comment]
See #1535

**Comment by marco-c** [comment]
I think this was an unfortunate case of Ryan and the bot acting at exactly the same time. When the bot was processing the bug, Ryan hadn't done his action yet.
