### ISSUE TITLE
fuzz_blockers.py misses some bugs

### ISSUE THREAD

**Issue by mathewhodson** [mozilla/relman-auto-nag#1582]
Some bugs such as https://bugzilla.mozilla.org/show_bug.cgi?id=768756 set the whiteboard like `
[fuzzblocker:editor-assertions]`. Those are getting missed.

_Originally posted by @mathewhodson in https://github.com/mozilla/relman-auto-nag/pull/1564#discussion_r933602912_

**Comment by marco-c** [comment]
Good catch, thanks for reporting!

**Comment by suhaibmujahid** [comment]
Thank you for reporting this. We reached out to the fuzzing team, who confirmed that this format is no longer supported. The fuzzing team is cleaning open bugs with such a tag format.

> [Tyson](https://matrix.to/#/!fKDCypxwedIOzgALgc:mozilla.org/$IH_A5TAV-3BLoRaPc1cqAZtAr3pMiFgUlZ3DEPC4A90?via=mozilla.org&via=matrix.org&via=envs.net):
> We have only been using [fuzzblocker] for at least 3(?) years now
