### ISSUE TITLE
[component] keywords should not be reset when bot changes Bugzilla component (+ potentially product)

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla/relman-auto-nag#1601]
https://bugzilla.mozilla.org/show_bug.cgi?id=1782636#c1 moved the bug to a different Bugzilla component and dropped the keywords. They should persist.

**Comment by marco-c** [comment]
That looks like a Bugzilla bug

**Comment by Archaeopteryx** [comment]
Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1782806

**Comment by dklawren** [comment]
Can we double check that auto-nag is not doing this because I am not aware of any code in BMO that modifies keywords when a component is changed. 

According to the bug history the keyword changes were made by release-mgmt-account-bot@mozilla.tld.

**Comment by marco-c** [comment]
It's strange because the component script only touches product and component, maybe adds somebody to CC and adds a comment (the script is at https://github.com/mozilla/relman-auto-nag/blob/master/auto_nag/scripts/component.py), but it definitely doesn't touch keywords.

**Comment by dklawren** [comment]
This did end up being a bug in the triage code introduced recently in BMO and a fix has been merged. We will deploy the fix live on Monday due to tomorrow being a company holiday.

**Comment by marco-c** [comment]
Thanks!
