### ISSUE TITLE
Very old bugs are listed in [autonag] Bugs to triage email

### ISSUE THREAD

**Issue by hsinyi** [mozilla/relman-auto-nag#1608]
We started to have very old bugs, e.g. [570164](https://bugzilla.mozilla.org/show_bug.cgi?id=570164),  [617068](https://bugzilla.mozilla.org/show_bug.cgi?id=617068), [654520](https://bugzilla.mozilla.org/show_bug.cgi?id=654520) in our daily triage autonag email. I am not sure if there's any triage guideline change that we want to review those old issues. However, there might be something wrong and apparently a different thing just happened this week.

Here's the bugzilla query in today's autonag email: [[autonag] Bugs to triage ](https://bugzilla.mozilla.org/buglist.cgi?keywords=intermittent-failure&keywords_type=nowords&email2=wptsync%40mozilla.bugs&emailreporter2=1&emailtype2=notequals&resolution=---&f1=bug_type&o1=equals&v1=defect&f2=flagtypes.name&o2=notsubstring&v2=needinfo%3F&f3=bug_severity&o3=anyexact&v3=--%2C%20n%2Fa&f4=status_whiteboard&o4=notsubstring&v4=%5Bno-nag%5D&f5=keywords&o5=nowords&v5=meta&j6=OR&f6=OP&f7=OP&f8=product&o8=equals&v8=Core&f9=component&o9=equals&v9=DOM%3A%20Copy%20%26%20Paste%20and%20Drag%20%26%20Drop&f10=CP&f11=OP&f12=product&o12=equals&v12=Core&f13=component&o13=equals&v13=DOM%3A%20Core%20%26%20HTML&f14=CP&f15=OP&f16=product&o16=equals&v16=Core&f17=component&o17=equals&v17=DOM%3A%20Editor&f18=CP&f19=OP&f20=product&o20=equals&v20=Core&f21=component&o21=equals&v21=DOM%3A%20Events&f22=CP&f23=OP&f24=product&o24=equals&v24=Core&f25=component&o25=equals&v25=DOM%3A%20Forms&f26=CP&f27=OP&f28=product&o28=equals&v28=Core&f29=component&o29=equals&v29=DOM%3A%20Navigation&f30=CP&f31=OP&f32=product&o32=equals&v32=Core&f33=component&o33=equals&v33=DOM%3A%20Selection&f34=CP&f35=OP&f36=product&o36=equals&v36=Core&f37=component&o37=equals&v37=DOM%3A%20Serializers&f38=CP&f39=OP&f40=product&o40=equals&v40=Core&f41=component&o41=equals&v41=DOM%3A%20UI%20Events%20%26%20Focus%20Handling&f42=CP&f43=OP&f44=product&o44=equals&v44=Core&f45=component&o45=equals&v45=XML&f46=CP&f47=CP&list_id=16168651)

**Comment by suhaibmujahid** [comment]
This is an empact of a recent change where we dropped the time limitation of 1 year (#1594). This change is to match the rules on [triage center](https://mozilla.github.io/triage-center). You can see the mentioned bugs in the "Triage decision needed" section:

<img width="1077" alt="image" src="https://user-images.githubusercontent.com/4151357/182856752-1b884388-67d8-415e-b4e0-3f8ca89a229c.png">

The total number of bugs affected by this change is 18 bugs. These bugs are distributed over multiple teams and components; details in https://github.com/mozilla/relman-auto-nag/issues/1592#issuecomment-1201719700.

**Comment by marco-c** [comment]
> This change is to match the rules on [triage center](https://mozilla.github.io/triage-center).

For reference, the rules that triage center is following (and now we are following too) are described at https://firefox-source-docs.mozilla.org/bug-mgmt/policies/triage-bugzilla.html.

**Comment by hsinyi** [comment]
Thank you for the references and context, appreciated!
