### ISSUE TITLE
Refactor the scripts to share the common code

### ISSUE THREAD

**Issue by sylvestre** [mozilla/relman-auto-nag#161]
In https://github.com/mozilla/relman-auto-nag/tree/master/auto_nag/scripts, we have a bunch of scripts.
Because @calixteman and myself are lazy, we have been duplicating the code.
Now that we are using it more and more, we shouldn't be doing that anymore.

For example, https://github.com/mozilla/relman-auto-nag/blob/master/auto_nag/scripts/no_assignee.py#L118
get_email is duplicated, ditto for send_email, get_login_info, etc

We should create a common file providing these functions with argument to manage the differences (mostly strings it seems)

**Comment by sannanansari** [comment]
You can guide me on this because I never solve bug. This my first time.

**Comment by sylvestre** [comment]
Sorry, Calixte just implemented the change :/

**Comment by calixteman** [comment]
Fixed now.
