### ISSUE TITLE
[bisection_without_regressed_by] Reference "comment #0" as "the description"

### ISSUE THREAD

**Issue by suhaibmujahid** [mozilla/relman-auto-nag#1626]
Example: https://bugzilla.mozilla.org/show_bug.cgi?id=1782411#c2

**Comment by marco-c** [comment]
Is "the description" automatically linkified like "comment 0"?

**Comment by suhaibmujahid** [comment]
> Is "the description" automatically linkified like "comment 0"?

"comment #0" is the description. So linking to `#c0` will be linking to the description. We are just changing the text, not the link.

**Comment by marco-c** [comment]
Oh, ok, I didn't realize we were adding a link as part of the comment. We actually don't need to do that, Bugzilla automatically adds a link when you mention a comment (see for example the "comment 1" link in https://bugzilla.mozilla.org/show_bug.cgi?id=1788277#c5).

**Comment by marco-c** [comment]
I think it's customary for people to mention "comment 0" (e.g. https://bugzilla.mozilla.org/show_bug.cgi?id=1774697#c2), I think I've never seen people mentioning "the description".
Probably we should keep things like they are, just removing the link as it is not required.

**Comment by suhaibmujahid** [comment]
I will do that.
