### ISSUE TITLE
Increase minimum crash count threshold for the "top crash" nag (from 5 to ?)

### ISSUE THREAD

**Issue by cpeterso** [mozilla/relman-auto-nag#1656]
autonag flagged me about a "top crash" on Fenix Nightly 107, but there are only three crash reports since Nightly 107 started just two days ago: https://bugzilla.mozilla.org/show_bug.cgi?id=1536505

Suggestion: maybe the top crash nag should have a minimum crash count before commenting on a top 10 crash bug. I don't know what would be an appropriate minimum because the number of Firefox users varies a lot on different platforms. But maybe 10 or 20 crashes?

This same crash was top crash 10 during Fenix Nightly 106, though it only had 50 crash reports for the entire four-week cycle. In contrast, other Fenix Nightly crash signatures had hundreds of crash reports.

**Comment by suhaibmujahid** [comment]
> autonag flagged me about a "top crash" on Fenix Nightly 107, but there are only three crash reports since Nightly 107 started just two days ago: https://bugzilla.mozilla.org/show_bug.cgi?id=1536505

Autonag is simply applying the [top crash identification criteria](https://wiki.mozilla.org/CrashKill/Topcrash). With that, we have a minimum of 5 crashes per week. Based on the Socorro, the signature has 47 crash reports  from 21 installations:

```json
{
  "term": "android.view.WindowManager$BadTokenException: at android.view.ViewRootImpl.setView(ViewRootImpl.java)",
  "count": 47,
  "facets": { "cardinality_install_time": { "value": 21 }, "startup_crash": [] }
}
```

> maybe the top crash nag should have a minimum crash count before commenting on a top 10 crash bug.

We already have a minimum of 5 crashes per week:

https://github.com/mozilla/relman-auto-nag/blob/6c00d1207cc9c8801ca374796a3f30d52ac8a9a0/auto_nag/topcrash.py#L223


> I don't know what would be an appropriate minimum because the number of Firefox users varies a lot on different platforms. But maybe 10 or 20 crashes?

@gabrielesvelto do you think we should increase the threshold from 5 to 10 or 20?


> This same crash was top crash 10 during Fenix Nightly 106, though it only had 50 crash reports for the entire four-week cycle. In contrast, other Fenix Nightly crash signatures had hundreds of crash reports.

@cpeterso do you mean that while marking the mentioned bug as topcrash crash, other bugs linked to crashes with higher volume are not marked as topcrash? If so, could you give an example to help debug the issue?

**Comment by suhaibmujahid** [comment]
Here is the Socorro query for Fenix AArch64 and ARM crashes on nightly: https://crash-stats.mozilla.org/api/SuperSearch/?_aggs.signature=_cardinality.install_time&_aggs.signature=startup_crash&_facets_size=527&_results_number=0&cpu_arch=arm64&cpu_arch=arm&date=%3E%3D2022-09-14&date=%3C2022-09-21&product=Fenix&release_channel=nightly

**Comment by cpeterso** [comment]
> @cpeterso do you mean that while marking the mentioned bug as topcrash crash, other bugs linked to crashes with higher volume are not marked as topcrash? If so, could you give an example to help debug the issue?

Sorry I wasn't clear. I didn't mean to suggest there was an autonag problem with the higher volume crash bugs. I was just using the higher volume crashes to show that bug 1536505's three crash reports is very low and not because we hadn't had time to receive plenty of other crash reports.

> Here is the Socorro query for Fenix AArch64 and ARM crashes on nightly: https://crash-stats.mozilla.org/api/SuperSearch/?_aggs.signature=_cardinality.install_time&_aggs.signature=startup_crash&_facets_size=527&_results_number=0&cpu_arch=arm64&cpu_arch=arm&date=%3E%3D2022-09-14&date=%3C2022-09-21&product=Fenix&release_channel=nightly

I was looking at crash-stat's top 50 browser crashes page:

https://crash-stats.mozilla.org/topcrashers/?product=Fenix&version=107.0a1

Both that page and this Super Search for the same range as your query shows only 8 crash reports:

https://crash-stats.mozilla.org/search/?signature=%3Dandroid.view.WindowManager%24BadTokenException%3A%20at%20android.view.ViewRootImpl.setView%28ViewRootImpl.java%29&product=Fenix&version=107.0a1&date=%3E%3D2022-09-14T19%3A18%3A00.000Z&date=%3C2022-09-21T19%3A18%3A00.000Z&_facets=signature&_sort=-date&_columns=date&_columns=signature&_columns=product&_columns=version&_columns=build_id&_columns=platform#facet-signature

I'm not sure why your query finds 47 crash reports and mine only finds 8...

**Comment by cpeterso** [comment]
In that case, we can probably close this bug as WONTFIX, leaving the minimum crash count threshold at 5.

**Comment by suhaibmujahid** [comment]
Thank you @cpeterso for reporting this.
