### ISSUE TITLE
 Exclude the "Common CA Database" component from autonag

### ISSUE THREAD

**Issue by WilsonKathleen** [mozilla/relman-auto-nag#1658]
Please exclude the "NSS :: Common CA Database" component from autonag.

I am now using both priority and severity to indicate order of work on the enhancement requests for the Common CA Database. We set all of our CCADB bugs to tasks, and would like to make sure that we won't get autonag reminders due to our severity settings.

Thanks,
Kathleen

**Comment by marco-c** [comment]
@WilsonKathleen autonag is only sending notifications for "defect" bugs that do not have a severity set, which shouldn't affect your workflow if I'm not mistaken.

**Comment by WilsonKathleen** [comment]
Excellent! Then I'm OK with setting severity on our Tasks.  Thanks!
