### ISSUE TITLE
Have a bot holiday

### ISSUE THREAD

**Issue by tnikkel** [mozilla/relman-auto-nag#1687]
It would be great if the bots went on holiday for a while to reduce the pressure on people. Imagine going from being stuck in a noisy traffic jam with cars honking to an serene secluded beach that no one else knows about. That would be what a bot holiday is like.

**Comment by marco-c** [comment]
Unfortunately I don't think this would be feasible, some of the bot actions require quick turnaround.

We have a triage owner rotation to try and reduce the load, spreading it across a few people. Your team is currently excluded, so you are not reaping the benefits of that yet.

**Comment by tnikkel** [comment]
I'm talking about the actions that don't need quick turn around. Those could easily be skipped for a while.
