### ISSUE TITLE
Disable "idle user" bugmail

### ISSUE THREAD

**Issue by tnikkel** [mozilla/relman-auto-nag#1689]
If the assignee etc were idle for a long period of time and nothing else is going on in the bug then very very likely that bug is not important and we shouldn't be wasting time getting people to look at it. Other problems with this: reminders of colleagues that have left are sad making. Reminder of people that have died are further sad making.

**Comment by marco-c** [comment]
Thanks to the "idle user" tool, we have been able to close many old bugs (a non-negligible percentage with actual fixes). Also, we have received positive feedback from the survey about it, so we won't remove it just yet.
We are certainly open to adjust the time it takes for people to be considered "idle" (e.g. if you have examples where it was too soon), or to reduce the frequency of the notifications, if that would help.

**Comment by tnikkel** [comment]
Sure, but many many more were useless old bugs that aren't important or even exist anymore. If we want to go be anecdata.

**Comment by tnikkel** [comment]
And in my experience the ratio is quite bad (ie its mostly un-important, useless, or non-existant bugs).
