### ISSUE TITLE
Wait more with nagging about severity until bug inactivity

### ISSUE THREAD

**Issue by Rob--W** [mozilla/relman-auto-nag#1694]
The bot nags about missing severity, which is rarely useful to me and my team.

One general case is when there are ongoing questions and comments with the reporter or others to determine whether the bug is valid. It is not helpful if the bot throws a needinfo while that is ongoing.

In today's example on a non-public bug, I got a needinfo about the severity not being set even though I posted a comment 4 days prior.

I sent suggest to only nag about severity if the bug has not had activity for at least two weeks.

**Comment by marco-c** [comment]
@Rob--W could you CC me and @suhaibmujahid on the bug?
Currently, the bot ignores bugs that have been open for less than two weeks, bugs which had recent activity (3 working days), bugs with a needinfo pending.

**Comment by Rob--W** [comment]
2022-10-14 21:30 CEST = last comment (Friday)
2022-10-18 14:06 CEST = [bot nag](https://bugzilla.mozilla.org/show_bug.cgi?id=1792138#c14) (Tuesday)

Doesn't look like 3 full working days have passed.
3 days is too short for recent activity. Could it be changed to at least 7, preferrably 14 days? Otherwise we will get an inactionable request to assign severity if triaging takes time. With weekly bug triage, there is a weekly check in on a bug. If a bug requires back-and-forth conversation, we will end up getting nagged by the bot without there being a way to act on it. At that point the botnag is just spam on the bug.

**Comment by marco-c** [comment]
Discussed on Matrix, in this specific example the bot partially helped, as it did actually prompt Rob to change the component, but there are cases where it is too soon.
We should:
- Wait 4 working days instead of 3 days;
- If the component changes, wait 2 weeks (but maybe we already do this?).

Then reassess if it is enough or we should modify it further.

**Comment by marco-c** [comment]
Perhaps, to help developers in future interactions with the bot, we could also slightly adjust the comment and mention something like "If you are waiting for information from someone, please set needinfo to them so I know that I have to wait.".

**Comment by marco-c** [comment]
And maybe instead of "The severity field is not set for this bug." say "The severity field is not set for this bug, two weeks after creation time (or since it was moved) and four working days after the last activity", so people know what the current rules are.
