### ISSUE TITLE
Do not update release status flags if the do-not-track keyword is set

### ISSUE THREAD

**Issue by DonalMe** [mozilla/relman-auto-nag#1710]
Sometimes older regressions bugs are not tracked by RelMan.
Current Behavior: metadata in a regression bug changes AND some conditions are met THEN the bot will add all current tracking flags with the status affected.

RelMan would like to leverage the do-not-track keyword. 
If a regression bug has the do-not-track keyword, then do not add additional tracking flags.

Example: https://bugzilla.mozilla.org/show_bug.cgi?id=1345667 older bug where the bot set the tracking flags. The bot continued to add newer tracking versions. In this example, RelMan could set do-not-track to prevent the bot from adding new versions

**Comment by DonalMe** [comment]
@marco-c #1535 will really help, thanks for mentioning it. 
The problem in my above example would have been handled by #1535!
I was under the impression if the latest version on the bug was wontfix, then the bot would not set later versions. 
Maybe #1535 will be enough

**Comment by marco-c** [comment]
All right, let's fix #1535 first, and then we'll re-evaluate if there is a need for this!

**Comment by DonalMe** [comment]
Also, on this point "more work for you (setting the keyword)."
relman are ok with setting a keyword when needed. It would save us additional steps later, e.g. maintining status for bugs that are in the backlog and shouldn't be tracked with each release. 
I don't expect we would have to use the keyword that often, it would only be for edge cases that #1535 doesn't handle. Though I can't think off hand of any edge case.

**Comment by marco-c** [comment]
@DonalMe it's been a few months now that #1535 has been live, do you feel this is still desirable or is the situation good now?

**Comment by DonalMe** [comment]
@marco-c thanks for checking - #1535 is working well so far. 
I don't think we need any further action here, the situation is good now.

**Comment by suhaibmujahid** [comment]
Thank you, @DonalMe!
