### ISSUE TITLE
Don't add a bug to Regressed By if it was previously removed

### ISSUE THREAD

**Issue by marco-c** [mozilla/relman-auto-nag#1738]
For example, in https://bugzilla.mozilla.org/show_bug.cgi?id=1675139 or https://bugzilla.mozilla.org/show_bug.cgi?id=1782411.

**Comment by suhaibmujahid** [comment]
We already exclude bugs that their `Regressed by` ever changed:

 https://github.com/mozilla/relman-auto-nag/blob/5363be84664c2dcc46582843eba3ea5f69fc38a9/auto_nag/scripts/bisection_without_regressed_by.py#L155-L157

Probably this is a regression from https://github.com/mozilla-bteam/bmo/pull/1952

**Comment by suhaibmujahid** [comment]
Fixed by https://github.com/mozilla-bteam/bmo/pull/1956
