### ISSUE TITLE
AMD64 and x86 are not relevant for top crashes for Android products

### ISSUE THREAD

**Issue by kbrosnan** [mozilla/relman-auto-nag#1780]
* Geckoview
* Focus
* Fenix

We don't have enough users to generate consistent top crash tables for AMD64 and x86. If we are not already monitoring ARM AArch64 and AArch32 should be used.

https://bugzilla.mozilla.org/show_bug.cgi?id=1801371#c2

**Comment by suhaibmujahid** [comment]
@kbrosnan thank you for reporting this. Could you please update the top crash criteria for Fenix on the wiki page (https://wiki.mozilla.org/CrashKill/Topcrash)? I will reflect your changes on the autonag bot.

CC @gabrielesvelto
