### ISSUE TITLE
 Don't mark a bug as invalid that I just marked as valid (part 2)

### ISSUE THREAD

**Issue by amccreight** [mozilla/relman-auto-nag#1789]
Thanks for working on addressing this issue in #1769. However, it doesn't seem to have entirely solved the issue.

In a [recent bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1801629), the bot marked as invalid a bug I thought was clearly a valid issue, so I reopened it. Then, a triager in the component changed the bug from REOPENED to UNCONFIRMED, presumably because they wanted to move it into some particular triaging bucket. Then the bot came around and marked the bug invalid again,  causing the triager to have to reopen the bug again, then re-mark it as unconfirmed. That was yesterday, so hopefully it won't get marked invalid a third time.

**Comment by amccreight** [comment]
I guess this is more about finding that an issue is not invalid, rather than the issue is confirmed as something that really happens.

**Comment by suhaibmujahid** [comment]
Thank you for reporting this, @amccreight! Resolving https://github.com/mozilla/bugbug/issues/2786 should increase the bot's accuracy when dealing with Thunderbird bugs.

In the meantime, we could make the bot avoid touching bugs that were moved out of the `Invalid Bugs` product.
