### ISSUE TITLE
Change the bug type to `defect` when setting the `regression` keyword

### ISSUE THREAD

**Issue by suhaibmujahid** [mozilla/relman-auto-nag#1796]
Example: https://bugzilla.mozilla.org/show_bug.cgi?id=1803207#c7

**Comment by suhaibmujahid** [comment]
I think this could be implemented as a rule in Bugzilla itself. 

@dklawren wdyt?

**Comment by dklawren** [comment]
> I think this could be implemented as a rule in Bugzilla itself.
> 
> @dklawren wdyt?

We can do that. Open a bug and I can take a look. Will be after the first of the year though.

**Comment by suhaibmujahid** [comment]
> Open a bug and I can take a look. 

I filed a bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1811647

**Comment by suhaibmujahid** [comment]
Fixed by https://github.com/mozilla-bteam/bmo/pull/2005
