### ISSUE TITLE
[severity_high_performance_impact] Collect stats about responses to the tool

### ISSUE THREAD

**Issue by suhaibmujahid** [mozilla/relman-auto-nag#1802]
Suggested by @mozilla:
> we should collect some stats about it to see how frequently the severity is increased after the needinfo
> and how frequently the needinfo is cancelled without action

**Comment by marco-c** [comment]
Could be part of @Archaeopteryx's script to collect other stats about autonag

**Comment by Archaeopteryx** [comment]
Of 21 needinfo requests, 16 got answered, and 4 of them the severity changed.

**Comment by marco-c** [comment]
We can call this done.
