### ISSUE TITLE
Consider more of a cooldown for changing topcrash

### ISSUE THREAD

**Issue by amccreight** [mozilla/relman-auto-nag#1811]
On 2022-12-13, both bug 1563825 and bug 1800558 had their topcrash keyword cleared, after having had it for 2 or 3 months, then 24 hours later they were re-added. This adds a lot of noise. (Although I will admit for bug 1800558 it did get me to do something...)

**Comment by marco-c** [comment]
We do have a cooldown period, not sure why it wasn't respected in this case. CC @suhaibmujahid

**Comment by suhaibmujahid** [comment]
> This adds a lot of noise.

I agree this is annoying. 

> We do have a cooldown period, not sure why it wasn't respected in this case.

We have a cooldown period before removing the `topcrash` but not before reading it. We could have the same before reading, but then the bot will be late to notify when the situation changes.

Another idea could be reading only if the crash has a recent spick.

**Comment by marco-c** [comment]
Maybe we could adjust the wording and say "sorry for removing but there was a recent spike, so this is again a tropcrash"?

**Comment by suhaibmujahid** [comment]
> Maybe we could adjust the wording and say "sorry for removing but there was a recent spike, so this is again a tropcrash"?

I agree we should customize the wording when we re-add the `tropcrash` keyword. In the mentioned examples, there are no recent spikes (in the last week). So we may need to measure for that before re-adding the keyword.
