### ISSUE TITLE
fixup qe-verify? to qe-verify+

### ISSUE THREAD

**Issue by kbrosnan** [mozilla/relman-auto-nag#1817]
TIL `qe-verify` does not work like any other flags in Bugzilla. `?` has no meaning and `+` is what gets QE/QA attention. Autonag should fixup any issues with `?` to `+`.

https://bugzilla.mozilla.org/buglist.cgi?quicksearch=flag%3Aqe-verify%3F

**Comment by marco-c** [comment]
Thanks, this is a great idea.
I wonder if we shouldn't simplify this field to make it clearer. If '?' is never used, we could change the field to only accept '---' or '+'.

**Comment by marco-c** [comment]
I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1809171.

**Comment by marco-c** [comment]
Fixed on Bugzilla.
