### ISSUE TITLE
Bot probably shouldn't ask regression-author to set the severity field on regressions, particularly if they're not full-time MoCo folks

### ISSUE THREAD

**Issue by dholbert** [mozilla/relman-auto-nag#1822]
Quoting https://bugzilla.mozilla.org/show_bug.cgi?id=1807769#c3 :

> :mrobinson, since you are the author of the regressor, [bug 1791759](https://bugzilla.mozilla.org/show_bug.cgi?id=1791759), could you take a look? Also, could you set the severity field?

mrobinson is a community member (working at Igalia on some gecko features), and probably isn't familiar with our severity levels or triage process. We probably shouldn't be requesting that such folks set severity, since it's implicitly asking that they do one of the following (neither of which we really want to request for non-full-time folks):
(1) we're asking them to learn the details of the various rating-levels & triage process (which isn't super discoverable & is asking a lot of them)
...or:
(2) we're asking them to just make a gut assessment, e.g. "I dunno, on a scale of 1-5 this seems like a 4, so let's call this S4"

Also, it takes the bug out of the triage queue for the relevant component, which means the triagers in that component may not notice the bug (it won't be in the untriaged-bugs list).  This may or may not be OK, depending on how diligent the needinfo'd person is on following up on the bug.

So: the bot probably shouldn't be flagging arbitrary authors-of-regressing-bugs to set severity levels.  I'd suggest either removing that request, or that we only include it after doing some sort of "is this person likely to already understand our triage/severity-rating process" check (to the extent that we can implement such a check).

**Comment by dholbert** [comment]
Yeah, `editbugs` isn't a good signal here -- it's a very low bar.  We often just hand that out when folks have helped out on a bug or two (since they need it if they e.g. want to post a reduced testcase on a bug that they didn't themselves file).

I think `editbugs` might technically give users the *ability* to adjust Severity/Priority fields (and most other fields), but it's not at all a signal that they understand (or should concern themselves with understanding) our triage process.

**Comment by marco-c** [comment]
We could rely on the people.json then, and only do this if the user is in people.json.
