### ISSUE TITLE
Some emails should also include the title of the bug

### ISSUE THREAD

**Issue by sylvestre** [mozilla/relman-auto-nag#183]
For example, for _[autonag] Bug not affecting the release but affecting beta or nightly without the regression keyword_, it would be helpful to have the title of the bug

https://github.com/mozilla/relman-auto-nag/blob/master/auto_nag/bzcleaner.py
https://github.com/mozilla/relman-auto-nag/blob/master/auto_nag/scripts/unaffected_affected_no_reg.py
will probably have to be touched

**Comment by calixteman** [comment]
Fixed:
https://github.com/mozilla/relman-auto-nag/pull/197
