### ISSUE TITLE
Shouldn't change bug type to "defect" for regressions if they're set to "task"

### ISSUE THREAD

**Issue by gijsk** [mozilla/relman-auto-nag#1832]
If bug X that was a `task` bug does something wrong that is internal and has no direct user consequence, the regression bug is still a `task`, not a `defect`, and shouldn't be changed - but is still validly a regression, and the bot shouldn't claim otherwise.

**Comment by marco-c** [comment]
This warrants a broader discussion, the rule "regression" -> "defect" is defined somewhere in the Firefox Source Docs.

Do you have a specific example?

**Comment by gijsk** [comment]
(I ended up removing the "regressed by" ref and using "depends" instead to make the bot stop trying to mark it as defect etc. etc, but because it was over the weekend, I was effectively a bit late)

**Comment by gijsk** [comment]
I would be interested in the Firefox source docs link for what you describe. What I can imagine being reasonable is that regressions can't be enhancements - enhancements should be new/improved features, and requests for them shouldn't reasonably be regressions.

**Comment by suhaibmujahid** [comment]
> I would be interested in the Firefox source docs link for what you describe. 

Here it is in the Firefox source docs: https://firefox-source-docs.mozilla.org/bug-mgmt/processes/regressions.html#marking-a-regression-bug

**Comment by gijsk** [comment]
OK. So I see two ways forward here:

1. change the policy. Personally, I think it's peculiar to claim that tasks cannot cause other task regressions, but ymmv. Perhaps @sylvestre remembers discussions around this from when that document got written / migrated from github.
2. come up with a different way of tracking "regressing bug", probably by using depends/blocks, and therefore in situations like the above, needinfo the triage owner instead of automatically moving from `task` to `defect`, and ask them to choose if this is a task (and if so use blocks/depends) or a defect (and if so change the bug type to defect).

(1) seems easier to me but I'm biased...

**Comment by suhaibmujahid** [comment]
_A clarification question:_ since the cases mentioned in https://github.com/mozilla/relman-auto-nag/issues/1832#issuecomment-1375822222 require fixing unexpected behaviour induced by a previous task (even though end users do not see it), why do we should not consider the unexpected behaviours as defects?

**Comment by gijsk** [comment]
My understanding is that `defect` is only supposed to be used for something that actually affects users in some way (even if it's "just" e.g. performance, and the ultimate behaviour is otherwise the same). But these issues literally did not impact users, they were only code cleanup issues.

**Comment by marco-c** [comment]
The definition for defect at https://firefox-source-docs.mozilla.org/bug-mgmt/guides/bug-types.html is "regression, crash, hang, security vulnerability and any other reported issue", it doesn't mention that the issue must be directly impacting users.

**Comment by gijsk** [comment]
OK, so it sounds like this is just about me feeling like the distinction between defects/tasks should be about user impact, and this should be closed.
