### ISSUE TITLE
Move crash signatures in duplicate bug 

### ISSUE THREAD

**Issue by calixteman** [mozilla/relman-auto-nag#184]
For example, if bug 1 has signature "foo::bar()" and it's marked duplicate of bug 2 then check that this signature is in bug 2 too (probably auto-fix here).

**Comment by pascalchevrel** [comment]
https://bugzilla.mozilla.org/buglist.cgi?keywords=crash&keywords_type=allwords&list_id=14250024&emailtype1=notequals&chfield=%5BBug%20creation%5D&chfieldfrom=-6m&email1=intermittent-bug-filer%40mozilla.bugs&emailreporter1=1&resolution=DUPLICATE&chfieldto=Now&query_format=advanced&bug_status=RESOLVED

The query above shows crashes created over the last 6 months that were marked as duplicates (excluding intermittent-bug-filer@mozilla.bugs bugs). I am going to check manually that we don't have missing signatures in the opened bugs for the more recent top, but yes it would be good to automate that clean up :)
