### ISSUE TITLE
Automatically add a comment when a bug is moved to Core::Performance

### ISSUE THREAD

**Issue by julienw** [mozilla/relman-auto-nag#1887]
Hey,

When a bug is moved to the Core::Performance component, [our process involves adding a comment to request additional information from the reporter](https://wiki.mozilla.org/Performance/Triage#Moved_to_Core::Performance).

Would it be possible to automatically add this comment with a needinfo to the reporter whenever a bug is moved to Core::Performance?
Here is the text:
```
This bug was moved into the Performance component. Reporter, could you make sure the following information is on this bug?

 - For slowness or high CPU usage, capture a profile with http://profiler.firefox.com/ , upload it and share the link here.
 - For memory usage issues, capture a memory dump from about:memory and attach it to this bug.
 - Troubleshooting information: Go to about:support, click "Copy raw data to clipboard", paste it into a file, save it, and attach the file here.

Thank you.
```

We were thinking of some edge cases that should be taken care of:
* if the bug is moved by mistake => the bot could wait for ~1 day before adding a comment, to allow for a user to move the bug again.
* avoid adding the comment twice (if the bug is moved back and forth)

Thanks in advance!

cc @davehunt

**Comment by suhaibmujahid** [comment]
Yes, it is totally possible.

**Comment by suhaibmujahid** [comment]
I limited this automation to `defect` bugs. You could find a dry run in https://github.com/mozilla/relman-auto-nag/pull/1916#issuecomment-1454818117

@julienw should we ignore meta bugs?

**Comment by julienw** [comment]
Hey Suhaib, thanks for looking at this!
I believe it makes sense to limit to `defect` bugs. Ignoring `meta` bugs sounds like a good idea too! (even if they probably shouldn't be `defect` in the first place?).

**Comment by suhaibmujahid** [comment]
> Ignoring `meta` bugs sounds like a good idea too! (even if they probably shouldn't be `defect` in the first place?).

Thank you! Here is an example of a `meta` bug that its type is `defect`: https://bugzilla.mozilla.org/show_bug.cgi?id=1260981. Such cases will be excluded.
