### ISSUE TITLE
Notify pending ni on people who are inactive

### ISSUE THREAD

**Issue by sylvestre** [mozilla/relman-auto-nag#190]
For example, I cleared 12 need info on Jet (who left)
The account was marked as inactive.

Another example:
https://bugzilla.mozilla.org/user_profile?user_id=441971
The name is " nihsanullah@invalid.bugs (disabled) "

**Comment by calixteman** [comment]
An an ideal world we should have a strategy to replace the ni by an other one.
So maybe in a first step, when we detect a ni with inactive profile, replace it with a ni on the manager.
But we should have some complains...
Anyway, when adding a new people.json, we could get the diff to know the people who left.
@sylvestre what do you want to do exactly ?

**Comment by marco-c** [comment]
See also #1230 and #1231.

**Comment by marco-c** [comment]
See also #266.

**Comment by marco-c** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1527841 would make this easier, but we can also implement this by getting a list of needinfos and a list of inactive people and find the intersection.
