### ISSUE TITLE
Add [sp3] whiteboard tag to dependencies of the speedometer3 meta bug

### ISSUE THREAD

**Issue by davehunt** [mozilla/relman-auto-nag#1911]
We are using [jira-bugzilla-integration](https://github.com/mozilla/jira-bugzilla-integration) to track the work on improving our Speedometer 3 score. This requires adding a whiteboard tag of `[sp3]` or `[sp3-*]`. All relevant bugs should be tracked as a dependency of [the meta bug](https://bugzilla.mozilla.org/show_bug.cgi?id=speedometer3) but many are lacking the necessary whiteboard tag.

Could we have an automation that finds all dependencies of the meta bug (a max depth of 2 is probably enough) and adds `[sp3]` to the whiteboard if there isn't already a variation of this present?

This enhancement might be useful for other users of jira-bugzilla-integration, as it currently only identifies bugs to sync via whiteboard tag.

**Comment by davehunt** [comment]
@marco-c I have https://gist.github.com/davehunt/34a04705fb3445b1c6bb5535bec6eee8, which probably needs some additional scrutiny but looks like it will do what we need. At the moment it just creates a CSV file for verifying, but the commented code would update the bugs.

**Comment by marco-c** [comment]
Thanks!
Some pointers that will help for the implementation.
We have something "similar" in scope: https://github.com/mozilla/relman-auto-nag/blob/master/auto_nag/scripts/pdfjs_tag_change.py. It's just a matter of changing the query parameters in https://github.com/mozilla/relman-auto-nag/blob/aafe2ebd9c44a99e09cba11ae80002ba5ab5b154/auto_nag/scripts/pdfjs_tag_change.py#L47 and the logic of what to do with each bug in https://github.com/mozilla/relman-auto-nag/blob/aafe2ebd9c44a99e09cba11ae80002ba5ab5b154/auto_nag/scripts/pdfjs_tag_change.py#L25.

For recursively retrieving blocker bugs, we can do something similar to what this script was doing https://github.com/mozilla/relman-auto-nag/blob/37ba94d2cae821deb5cab067f613f9b2cc3a440c/auto_nag/scripts/fuzzing_bisection_without_regressed_by.py#L63.

**Comment by davehunt** [comment]
Let's hold off on this one for now - we're learning that we may want to have a manual triage of these bugs before adding the whiteboard tag.

**Comment by davehunt** [comment]
We’re achieving this through a local script run regularly. There’s no need to automate it at this time. Thank you for the help!
