### ISSUE TITLE
nagbot should not ask people to set regressed-by field on sec bugs, since that potentially leaks details about security issues

### ISSUE THREAD

**Issue by dholbert** [mozilla/relman-auto-nag#1921]
Right now, the nagbot is nudging[1] triage owners to set the regressed-by field on security-sensitive bugs, when it finds one with a regression range posted.

It should not be asking people to do that; that goes against our security bug process.  As noted in https://firefox-source-docs.mozilla.org/bug-mgmt/processes/security-approval.html#filing-managing-bugs , our best-practices are to "Avoid linking [security-sensitive bugs] to non-security bugs with Blocks, Depends, Regressions, or See Also"

[1] In the specific case that I saw (details redacted), the bot's comment was:
> Based on comment #N, this bug contains a bisection range found by bugmon. However, the Regressed by field is still not filled.
> [triage owner], if possible, could you fill the Regressed by field and investigate this regression?
> For more information, please visit auto_nag documentation.

(Ping me if we need more info about the specific bug/etc. here.)

**Comment by dholbert** [comment]
Ah, maybe this is OK after all; @rvandermeulen says that this documentation may be out of date, and users-who-can't-see-the-sec-bug will also not see the linkage, perhaps.

I'll leave this open in case Ryan or the bot-maintainers have additional thoughts/suggestions here, but it's possible we can close this as not-actually-an-issue.

**Comment by rvandermeulen** [comment]
Yeah, I already pinged Dan about updating the docs. You can confirm for yourself with the bug in question that the regressed by field isn't set when viewing it in PB mode. We added those safeguards to BMO awhile back.
