### ISSUE TITLE
auto-nag slowdown since September 2018

### ISSUE THREAD

**Issue by jcristau** [mozilla/relman-auto-nag#198]
For the last week or two auto-nag has been running much slower than before. I don't know if some bugzilla queries are taking longer or something else, but somebody should do something™.

**Comment by calixteman** [comment]
Yesterday I observed that sending one mail was super long (several minutes) so maybe something is wrong with smtp server.

**Comment by calixteman** [comment]
It should be fixed now:
https://bugzilla.mozilla.org/show_bug.cgi?id=1494293
