### ISSUE TITLE
When an autofix operation is failing, autonag retries everything

### ISSUE THREAD

**Issue by sylvestre** [mozilla/relman-auto-nag#234]
we should either stop the whole process
or just retry on the non processed stuff

**Comment by calixteman** [comment]
I made a PR on libmozdata to handle that case:
https://github.com/mozilla/libmozdata/pull/135

**Comment by calixteman** [comment]
It has been done in refactoring bzcleaner:
https://github.com/mozilla/relman-auto-nag/commit/0255ea09abfb0fc2bcd30e4a406a6a411d3438d2

Now each bug is updated one by one.
