### ISSUE TITLE
Add an autofix to the meta bug

### ISSUE THREAD

**Issue by sylvestre** [mozilla/relman-auto-nag#240]
here, we should add an autofix.
https://github.com/mozilla/relman-auto-nag/blob/master/auto_nag/scripts/meta_summary_missing.py#L43
I am not sure how to do it        

Should be something like
`return {'summary': '[meta]' + summary`

**Comment by calixteman** [comment]
Fixed in:
https://github.com/mozilla/relman-auto-nag/commit/056da5f25e7f0afaaa747a60827513800d0dce79
