### ISSUE TITLE
When a script has an autofix, update the subject of the mail to indicate it

### ISSUE THREAD

**Issue by sylvestre** [mozilla/relman-auto-nag#241]
Example
_[autonag] Bugs with no assignees for the 2018-11-07_
=> 
_[autonag][autofix] Bugs with no assignees for the 2018-11-07_

**Comment by calixteman** [comment]
Fixed in https://github.com/mozilla/relman-auto-nag/commit/dd1f8b86c2c1aea298d1d7d057ac81ce15420787
