### ISSUE TITLE
status flags of nightly should be updated when the bug is reopened

### ISSUE THREAD

**Issue by sylvestre** [mozilla/relman-auto-nag#244]
Example:

https://bugzilla.mozilla.org/buglist.cgi?f1=cf_status_firefox65&o1=anyexact&resolution=---&query_format=advanced&v1=fixed%2C%20wontfix

![image](https://user-images.githubusercontent.com/733326/48230752-60a36080-e3ac-11e8-8226-55d23a1cc5a8.png)

**Comment by calixteman** [comment]
Fixed in https://github.com/mozilla/relman-auto-nag/commit/13a5d32131205e12bb3a47513f8b9a899a9d0809
