### ISSUE TITLE
Should warn when a bug is fixed in nightly, tracked in aurora & beta but no uplift request

### ISSUE THREAD

**Issue by sylvestre** [mozilla/relman-auto-nag#25]
For example, in https://bugzilla.mozilla.org/show_bug.cgi?id=1194706 , Liz had to ping the developer. The developer should receive a notification.

**Comment by lizzard** [comment]
Maybe even when the bug is not tracked, but is marked as affected.

**Comment by sylvestre** [comment]
:+1:

**Comment by sylvestre** [comment]
We had the similar issue with this bug https://bugzil.la/1241558
I agree with Liz, even if it is not tracked, the release management team should receive an email.
Either uplift or wontfix in the branch.

**Comment by calixteman** [comment]
In this commit:
https://github.com/calixteman/relman-auto-nag/commit/b81b18382a55fa018a9cdef4ce5564662215bbf1?diff=unified

I added a script to add this feature.

**Comment by sylvestre** [comment]
Fixed
