### ISSUE TITLE
Add a keword or a checker to prevent Release mgmt bot to auto-correct bug status

### ISSUE THREAD

**Issue by mayhemer** [mozilla/relman-auto-nag#255]
Sometimes we want to keep assigned bugs in the UNCONFIRMED state to: 1. not get lost from the radar, 2. dedicate a person to work on the confirmation that may not always be straight forward, 3. make it visible that the bug may not be in our code

**Comment by calixteman** [comment]
So just add [no-nag] in whiteboard and the bot will ignore it:
e.g. https://bugzilla.mozilla.org/show_bug.cgi?id=1303314

**Comment by mayhemer** [comment]
Thanks!
