### ISSUE TITLE
bugzilla/ & scripts/ should be moved into a common directory

### ISSUE THREAD

**Issue by sylvestre** [mozilla/relman-auto-nag#26]
To follow what is usually done in the Python world, we should create a new directory
auto-nag/
and move bugzilla/ & scripts/ into it.

It will probably require some changes in import and so.
Hopefully, this will also simplifies tests and code coverage executions.

**Comment by anoopvalluthadam** [comment]
@sylvestre you are talking about inside the  project ROOT folder auto-nag/ then

auto-nag/scripts
auto-nag//bugzilla

like this?

**Comment by sylvestre** [comment]
Exactly :) 

Le 14 octobre 2015 11:22:30 GMT+02:00, Anoop Valluthadam <notifications@github.com> a écrit :
>@sylvestre you are talking about inside the  project ROOT folder
>auto-nag/ then
>
>auto-nag/scripts
>auto-nag//bugzilla
>
>like this?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/mozilla/relman-auto-nag/issues/26#issuecomment-147987233

-- 
Envoyé de mon téléphone Android avec K-9 Mail. Excusez la brièveté.

**Comment by sylvestre** [comment]
Implemented by Anoop in https://github.com/mozilla/relman-auto-nag/pull/30
Thanks!
