### ISSUE TITLE
For every query, use the general list of products

### ISSUE THREAD

**Issue by sylvestre** [mozilla/relman-auto-nag#264]
List:
https://github.com/mozilla/relman-auto-nag/blob/master/auto_nag/scripts/configs/tools.json#L25
instead of duplicating:
https://github.com/mozilla/relman-auto-nag/blob/master/auto_nag/scripts/old_p1_bug.py#L14

**Comment by calixteman** [comment]
Done:
https://github.com/mozilla/relman-auto-nag/commit/c7e1ec0969661a8c493b9a6db3eb7fdd5f3d81ef
