### ISSUE TITLE
Unassign inactive people on bugs

### ISSUE THREAD

**Issue by pascalchevrel** [mozilla/relman-auto-nag#266]
Some bugs have an assignee but the person has not logged into Bugzilla in years so they should be unassigned to these bugs so as to reflect the reality that they won't fix them.

Example:
https://bugzilla.mozilla.org/user_profile?user_id=105243
user last activity on bugzilla: 
2015-06-01

But 29 bugs are still assigned to this person:
https://bugzilla.mozilla.org/buglist.cgi?list_id=14449526&emailtype1=exact&emailassigned_to1=1&email1=asaf%40sent.com&query_format=advanced&bug_status=UNCONFIRMED&bug_status=NEW&bug_status=ASSIGNED&bug_status=REOPENED

**Comment by sylvestre** [comment]
![image](https://user-images.githubusercontent.com/733326/49087659-d6864380-f257-11e8-9e09-8da061314191.png)
(because I will reset them)

**Comment by sylvestre** [comment]
The full query:
https://bugzilla.mozilla.org/buglist.cgi?list_id=14537708&o1=lessthaneq&o2=nowords&v1=2018-07-01&v2=nobody%40mozilla.org%2Cnobody%40nss.bugs&f1=assignee_last_login&resolution=---&classification=Client%20Software&classification=Developer%20Infrastructure&classification=Components&classification=Server%20Software&classification=Other&query_format=advanced&f2=assigned_to&product=Core&product=Firefox&product=Firefox%20Build%20System&product=Firefox%20for%20Android&product=Toolkit&product=WebExtensions

We should probably unassigned them and needinfo the triage owner

**Comment by calixteman** [comment]
The tool has been added in:
https://github.com/mozilla/relman-auto-nag/commit/0255ea09abfb0fc2bcd30e4a406a6a411d3438d2#diff-8e8954919b092f3dea2976a96bf61ef8
but it isn't activated yet.
@sylvestre what do we do here ?

**Comment by sylvestre** [comment]
I am still unsure what to do here... I guess most of them highlight useless
bugs.
Someone suggested that we do needinfo the triage owner when it was assigned
to a former employee. Wdyt?

**Comment by calixteman** [comment]
It isn't always easy to guess who is a former employee and I hope that there is not so many bugs like this. But for easy cases (bz mail ending with mozilla.com) we can do that.
For the other ones, I don't know...
@lizzard, @emceeaich, @pascalchevrel, @marco-c  wdyt ?

**Comment by pascalchevrel** [comment]
needinfo the triage owner is fine for me, bugs that are assigned to somebody that is not active are also bugs that can't be taken by volunteers btw. If the triage owner doesn't take any action in x months, we can decide to unassign then.

**Comment by emceeaich** [comment]
Searching for assignee = %group.mozilla-corporation% will find active staff and %group.editbugs% anyone with editbugs, but I can't think of anything we do that captures "was staff when assigned bug" but not staff now.

To avoid this in the future we should be un-assigning bugs when we off-board staff, and maybe create a mozilla-corporation-alumni group? I'll follow up in a BMO bug for the later.

**Comment by pascalchevrel** [comment]
I don't think that unassigning bugs from previous staff members is the way to go, you have people that left mozilla but still work on bugs that were assigned to them (xidorn and mounir for example or more recently dietrich) because their new job is compatible with contributing with Mozilla. it is the *activity* in the mozilla project that matters.

**Comment by marco-c** [comment]
I propose we unassign inactive people without adding a needinfo if the last activity in the bug is older than three months and add the needinfo if the last activity in the bug is more recent.
This way we'd add, at the moment, less than 40 needinfos.

What do you think? @calixteman @pascalchevrel @sylvestre

**Comment by pascalchevrel** [comment]
I think that 3 months is too short for people working on long term platform bugs (spec implementation for example) which is work that can span a couple of years.

**Comment by marco-c** [comment]
With 1 year it would be 100 needinfos. The problem with that is that we'd needinfo some triage owners on a lot of bugs (e.g. aosmond for Core::ImageLib).
My thinking is that this way we get to a clean slate without making too much noise, and for the future we are going to add needinfo on all bugs where the assignee is inactive.

**Comment by marco-c** [comment]
I've opened #1292 to start enabling it with the limitation on last activity, we can always change the limitation or remove it, but I think it's good to at least start somewhere.

**Comment by calixteman** [comment]
> I propose we unassign inactive people without adding a needinfo if the last activity in the bug is older than three months and add the needinfo if the last activity in the bug is more recent. This way we'd add, at the moment, less than 40 needinfos.
> 
> What do you think? @calixteman @pascalchevrel @sylvestre

Maybe it's a bit agressive...
So a plan could be:
 - send an email with the rationale on dev-platform or to the managers to warn people that we'll do some assignee removals
 - propose a keyword or whatever to allow to have exceptions, e.g. `long-term-bug`...
 - then close and nag.

**Comment by calixteman** [comment]
I deleted my previous message because I misunderstood the issue.
Anyway I'm fine to auto-remove assignee without a ni.
We can check in the next days how people are handling their ni: today I saw one dev who was just cancelling his nis.

**Comment by marco-c** [comment]
We have seen a few examples of good outcome from this, so we can slowly (maybe every 2 weeks) increase the last activity threshold (from 3 to 6 months, then from 6 months to 1 year, then from 1 year to 2 years, then we totally remove the threshold).
