### ISSUE TITLE
Automatically confirm bugs that have firefoxXX:affected flag

### ISSUE THREAD

**Issue by pascalchevrel** [mozilla/relman-auto-nag#270]
Example:
https://bugzilla.mozilla.org/show_bug.cgi?id=1511106

The bug status is unconfirmed, but a developer added metadata that shows this is a confirmed bug (firefox65:affected, regression…).

I think that if somebody who is not the reporter marks a specific firefox release as affected/unaffected, we should change the bug status  to NEW.

**Comment by calixteman** [comment]
@pascalchevrel, could give me a list of the relevant flags, keywords, ... which "prove" that the bug is NEW ?
@sylvestre any idea ?

**Comment by marco-c** [comment]
I'd say the most clear ones are the status flags.
I wouldn't use the `regression` keyword, as sometimes people set it even if the bug is actually unconfirmed. E.g. if the reporter says that it is a regression, but nobody could confirm the bug yet.

**Comment by calixteman** [comment]
@marco, pascal proposed that we should only consider bugs where the change has been made by someone except the reporter himself. Do you think it makes sense in that case ?

**Comment by marco-c** [comment]
I'm not sure, I remember cases where developers/triagers put `regression` even if the bug wasn't confirmed yet just because the reporter said it was a regression. It's possible that there are only few cases though.
For the status flags we can be definitely sure.

**Comment by marco-c** [comment]
See also #1238.

**Comment by suhaibmujahid** [comment]
> I think that if somebody who is not the reporter marks a specific firefox release as affected/unaffected, we should change the bug status to NEW.

@pascalchevrel why do we need to exclude the reporter? Is it allowed for a new reporter to mark a version as affected (i.e., add firefoxXX:affected flag).

**Comment by suhaibmujahid** [comment]
> Bugs marked as UNCONFIRMED are bugs opened by people with limited bug editing rights (typically end-users filing occasional bugs), they can't edit these fields.

Thank you @pascalchevrel, so in our case, it is safe to always assume that the reporter is not the one who added the `firefoxXX:affected` flag.

**Comment by suhaibmujahid** [comment]
In [bug 1753077](https://bugzilla.mozilla.org/show_bug.cgi?id=1753077#a67_699670) the reporter changed the following ` status-firefox96: --- → affected` and the bug status is `UNCONFIRMED`. Other bugs have similar situations (e.g., [1763796](https://bugzilla.mozilla.org/show_bug.cgi?id=1763796#a106_689505) and [1675967](https://bugzilla.mozilla.org/show_bug.cgi?id=1675967#a937901_659060)). @pascalchevrel wdyt?

**Comment by pascalchevrel** [comment]
> In [bug 1753077](https://bugzilla.mozilla.org/show_bug.cgi?id=1753077#a67_699670) the reporter changed the following ` status-firefox96: --- → affected` and the bug status is `UNCONFIRMED`. Other bugs have similar situations (e.g., [1763796](https://bugzilla.mozilla.org/show_bug.cgi?id=1763796#a106_689505) and [1675967](https://bugzilla.mozilla.org/show_bug.cgi?id=1675967#a937901_659060)). @pascalchevrel wdyt?

Interesting, I thought that people without the `editbug` flag shouldn't be able to modify these flags, that's something we should fix on bugzilla end, I'll file a ticket to prevent that.

**Comment by suhaibmujahid** [comment]
> Interesting, I thought that people without the `editbug` flag shouldn't be able to modify these flags, that's something we should fix on bugzilla end, I'll file a ticket to prevent that.

Thank you, Pascal! I filed a ticket regarding this, please see https://bugzilla.mozilla.org/show_bug.cgi?id=1764448
