### ISSUE TITLE
Mark  release N as '?' if release N-1 and N+2 have a status set

### ISSUE THREAD

**Issue by pascalchevrel** [mozilla/relman-auto-nag#271]
I often see bugs that have firefox status missing for a release, for example:

Firefox63: affected
Firefox65: affected

But 64 is missing so it doesn't show up in search results for this version. I think we should have n set to '?' at least when n-1 and n+2 have different values and set it to the same value as n-1 and n+1 if they are equal.

Examples:

**Before:**
Firefox63: affected
Firefox65: affected

**After:**
Firefox63: affected
Firefox64: affected
Firefox65: affected

**Before:**
Firefox63: wontfix
Firefox65: wontfix

**After:**
Firefox63: wontfix
Firefox64: wontfix
Firefox65: wontfix

**Before:**
Firefox63: wontfix
Firefox65: affected

**After:**
Firefox63: wontfix
Firefox64: ?
Firefox65: affected

**Comment by sylvestre** [comment]
Yeah, I am.
We might have some false positive in the first case (when we disable a feature) but they should be rare.

**Comment by sylvestre** [comment]
great idea btw
