### ISSUE TITLE
Add weekly closure of intermittent test failure bugs

### ISSUE THREAD

**Issue by emceeaich** [mozilla/relman-auto-nag#307]
Bugs in [this query](https://mzl.la/2fDG04N) should be `RESOLVED` as `INCOMPLETE`. 

Closing these bugs requires the use of the API key for the bug-husbandry account which does not send emails when changing bugs. 

The comment on bug should be:

```
https://wiki.mozilla.org/Bug_Triage#Intermittent_Test_Failure_Cleanup
```

**Comment by sylvestre** [comment]
@emceeaich there is a consensus on this one?
(like if we implement it tomorrow nobody will complain?)

**Comment by marco-c** [comment]
Duplicate of #310.

**Comment by emceeaich** [comment]
This is now running so will close.
