### ISSUE TITLE
Handling potential regressions found by bugbug

### ISSUE THREAD

**Issue by emceeaich** [mozilla/relman-auto-nag#312]
Now that we have bugbug predicting regressions should we

1. Set `needinfo` for triage owners of bugs predicted to be regressions?
2. Add the `regression` and `regressionwindow-wanted` keywords automatically?

**Comment by marco-c** [comment]
See also https://github.com/mozilla/relman-auto-nag/issues/284. My idea was to do 2 (but only the `regression` keyword, as there could already be a regression window noted in the bug. I'm working on another classifier which will try to tell whether there is already a regression window or not).

**Comment by marco-c** [comment]
Closing as duplicate of #284, which I'm fixing now.

**Comment by marco-c** [comment]
And #221 is about adding the regressionwindow-wanted keyword.
