### ISSUE TITLE
Check consistency of components managed in GitHub

### ISSUE THREAD

**Issue by emceeaich** [mozilla/relman-auto-nag#313]
Bugs in a component using an external repository which are resolved as `FIXED` without the `github-merged` keyword should be flagged by auto-nag so we can confirm code has landed in the right places.

See https://bugzilla.mozilla.org/show_bug.cgi?id=1520053

To start, look at the Activity Stream components.

**Comment by marco-c** [comment]
I think this keyword is no longer used.
