### ISSUE TITLE
leave-open-no-activity should ignore intermittent failures

### ISSUE THREAD

**Issue by marco-c** [mozilla/relman-auto-nag#348]
E.g. https://bugzilla.mozilla.org/show_bug.cgi?id=1331853 should be ignored, because it has `[stockwell disabled]` in the whiteboard.
So it looks like https://github.com/mozilla/relman-auto-nag/blob/4f8e9ba642f4897b45d700bb4c15b2178bc00b7f/auto_nag/scripts/leave_open_no_activity.py#L70 is not working.

We should probably also ignore bugs which have `intermittent` in the keywords.

**Comment by marco-c** [comment]
About the whiteboard, maybe it's because the bot commented there before we added the regex.

So we should just add the rule with the keyword.

**Comment by calixteman** [comment]
@marco-c you're right: https://bugzilla.mozilla.org/buglist.cgi?bug_id=1331853&bug_id_type=anyexact&f1=status_whiteboard&list_id=14554437&o1=notregexp&resolution=---&classification=Client%20Software&classification=Developer%20Infrastructure&classification=Components&classification=Server%20Software&classification=Other&query_format=advanced&v1=%5C%5B%28test%7Cstockwell%29%20disabled.%2A%5C%5D
is showing that the regex is ok.

**Comment by calixteman** [comment]
Fixed in https://github.com/mozilla/relman-auto-nag/pull/365.
