### ISSUE TITLE
Add tool to find the bugs where a person who is needinfoed didn't login for a long time

### ISSUE THREAD

**Issue by marco-c** [mozilla/relman-auto-nag#360]
See also #359.

**Comment by calixteman** [comment]
I filed a bug on Bugzilla:
https://bugzilla.mozilla.org/show_bug.cgi?id=1527841
Once it'll be fixed, this one will be easy to fix.

**Comment by marco-c** [comment]
See also #190.

**Comment by marco-c** [comment]
Duplicate of #190.
