### ISSUE TITLE
Detect bug with the topcrash* keywords or high severity with small volume and remove the keywords and decrease severity

### ISSUE THREAD

**Issue by sylvestre** [mozilla/relman-auto-nag#371]
exemple: https://bugzilla.mozilla.org/show_bug.cgi?id=530074

**Comment by marco-c** [comment]
Maybe we should reduce the severity too in cases where the volume is super low (e.g. 1 or 2 crashes per week).

@gabrielesvelto wdyt?

**Comment by gabrielesvelto** [comment]
It's fine by me, we can still manually bump it up if we feel like it (if we determine it's a security issue for example)
