### ISSUE TITLE
Port to Python Requests

### ISSUE THREAD

**Issue by bkerensa** [mozilla/relman-auto-nag#4]
We should consider porting the urllib and urllib2 code to python requests perhaps this could be a contribution opportunity or good first bug.

**Comment by anoopvalluthadam** [comment]
@bkerensa  @sylvestre I am working on it.

**Comment by sylvestre** [comment]
Ok, great, please write unit tests if you can :) 
(noise is fine) 

Le 22 août 2015 14:49:40 GMT+02:00, Anoop Valluthadam <notifications@github.com> a écrit :
>@bkerensa  @sylvestre I am working on it. 
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/mozilla/bztools/issues/4#issuecomment-133695555

-- 
Envoyé de mon téléphone Android avec K-9 Mail. Excusez la brièveté.

**Comment by anoopvalluthadam** [comment]
@sylvestre Cool, I will write unit test as well.

Hope you mentioned nose - https://nose.readthedocs.org/en/latest/

**Comment by sylvestre** [comment]
Yep, my bad, sorry :)

**Comment by sylvestre** [comment]
Implemented in the PR #29
