### ISSUE TITLE
Component: try to make a better guess for "Firefox build system"

### ISSUE THREAD

**Issue by calixteman** [mozilla/relman-auto-nag#422]
It seems to be obvious when we read the first comment:
https://bugzilla.mozilla.org/show_bug.cgi?id=1531745
https://bugzilla.mozilla.org/show_bug.cgi?id=1532169

**Comment by marco-c** [comment]
`Firefox Build System` is not in the list of products/components considered by bugbug, but we could add it if we want.
I filed https://github.com/mozilla/bugbug/issues/208 to consider it.
