### ISSUE TITLE
Exclude fix-optional or wontfix issues from the nag emails

### ISSUE THREAD

**Issue by lizzard** [mozilla/relman-auto-nag#457]
I'm getting nag emails for issues where the status-firefox66 flag is set to wontfix or fix-optional but the bug was tracked for 66, like this one https://bugzilla.mozilla.org/show_bug.cgi?id=1454639   
I tend to leave those tracked so that if the status changes, the issue will come up again in my tracking queries (which exclude fix-optional/wontfixed tracked bugs).

**Comment by calixteman** [comment]
There was something wrong with this template:
https://wiki.mozilla.org/Template:CURRENT_CYCLE
and so the query got some unrelated bugs like this one.

I fixed the issue:
https://github.com/mozilla/relman-auto-nag/pull/456
