### ISSUE TITLE
Port to new native REST API

### ISSUE THREAD

**Issue by bkerensa** [mozilla/relman-auto-nag#5]
Per announcement from Gerv below we should consider porting bztools to the new native REST API in the future but perhaps this would be a good first bug for a contributor.

"This service is due to be decommissioned. Fortunately, Bugzilla has a new native REST API which works somewhat similarly that you could use instead:
https://wiki.mozilla.org/Bugzilla:REST_API

Moving to that new API would require some porting work. If that seems like too much effort, fear not, because there is also a BzAPI compatibility layer built on top of the new API. Because it's compatible, using that should simply require a change of API endpoint.

Change:
https://api-dev.bugzilla.mozilla.org/latest/
(or https://api-dev.bugzilla.mozilla.org/1.3/)
to
https://bugzilla.mozilla.org/bzapi/"

**Comment by sylvestre** [comment]
@bkerensa are you still planning to work on this?

**Comment by bkerensa** [comment]
We should leave this as a Good First Bug to on ramp new contributors

**Comment by arunta007** [comment]
@sylvestre As a beginner, can I work on this if not already done?

**Comment by edmorley** [comment]
Note: I'd recommend doing this sooner rather than later, since BzAPI is 2-10x slower in many cases. See:
https://bugzilla.mozilla.org/show_bug.cgi?id=1301541
https://bugzilla.mozilla.org/show_bug.cgi?id=1035804
