### ISSUE TITLE
In the defect/enhancement/task email, show rows with 'defect' first

### ISSUE THREAD

**Issue by marco-c** [mozilla/relman-auto-nag#544]
enhancement vs task are less interesting, so we should show rows which contain 'defect' first.

**Comment by sylvestre** [comment]
Could you please also enable an autofix to the defect?

**Comment by marco-c** [comment]
> Could you please also enable an autofix to the defect?

An autofix that does "task/enhancement -> defect", or "defect -> task/enhancement", or both?

**Comment by sylvestre** [comment]
the first to start with

**Comment by marco-c** [comment]
OK, filed #545 for that.
