### ISSUE TITLE
Figure out a way to make scripts run when a Bugzilla change is made

### ISSUE THREAD

**Issue by marco-c** [mozilla/relman-auto-nag#555]
IIRC @kyoshino was working on something to notify clients of changes in Bugzilla.

There are some scripts (e.g. component assignment) which would be nice to run as soon as a bug is filed / changed, rather than hourly.

**Comment by marco-c** [comment]
There once was https://wiki.mozilla.org/BMO/ChangeNotificationSystem, but I think it has been decommissioned.

**Comment by kyoshino** [comment]
Yes, we don’t have any notification system now. Our hope is GraphQL: [Bug 1281087 - Re-implement Bugzfeed-like change notification system using GraphQL Subscriptions](https://bugzilla.mozilla.org/show_bug.cgi?id=1281087)

**Comment by marco-c** [comment]
#1107 is the way.
