### ISSUE TITLE
defectenhancementtask: add a link behind task to bug_type documentation in  Bugzilla comment

### ISSUE THREAD

**Issue by calixteman** [mozilla/relman-auto-nag#579]

**Comment by marco-c** [comment]
@emceeaich what is the right link we should use?

**Comment by calixteman** [comment]
I'd say: https://wiki.mozilla.org/BMO/UserGuide/BugFields#bug_type

**Comment by sylvestre** [comment]
yeah

**Comment by calixteman** [comment]
anyway, most of the fields have a doc link in the Bugzilla UI and bug_type doesn't and so we should add one.

**Comment by sylvestre** [comment]
agreed, could you please add an issue in our project in the bug mgmt board?

**Comment by marco-c** [comment]
Fixed by #587.
