### ISSUE TITLE
Regression nag on bug that's not a regression

### ISSUE THREAD

**Issue by linacambridge** [mozilla/relman-auto-nag#619]
The new `is_regression` flag might make this obsolete, but...[this comment](https://bugzilla.mozilla.org/show_bug.cgi?id=1544706#c1) is an example of a nag where the reporter wrote "This issue is not a regression" in the [description](https://bugzilla.mozilla.org/show_bug.cgi?id=1544706#c0).

**Comment by marco-c** [comment]
Should be more precise now.
