### ISSUE TITLE
Emails mention «Priority flag» whereas the field is called «Importance»

### ISSUE THREAD

**Issue by leplatrem** [mozilla/relman-auto-nag#626]
![Screenshot from 2019-05-02 14-04-08](https://user-images.githubusercontent.com/546692/57074101-3be8cf80-6ce3-11e9-89ef-ab13546c9f01.png)

![Screenshot from 2019-05-02 14-04-34](https://user-images.githubusercontent.com/546692/57074100-3b503900-6ce3-11e9-81b9-3c09d02cd634.png)

**Comment by calixteman** [comment]
I filed a bug:
https://bugzilla.mozilla.org/show_bug.cgi?id=1548506
