### ISSUE TITLE
In query_creator.py, the last arg of urls = (0) seems useless

### ISSUE THREAD

**Issue by sylvestre** [mozilla/relman-auto-nag#63]
In all of the cases, the last value is 0, we should figure out if this is necessary or not.

urls = [
    (5, ["Unlanded Beta " + beta_version + " Bugs", "unlanded_beta", unlanded_beta_url, 0]),
    (5, ["Unlanded Aurora " + aurora_version + " Bugs", "unlanded_aurora", unlanded_aurora_url, 0]),
    (5, ["Unlanded ESR38 Bugs", "unlanded_esr38", unlanded_esr38_url, 0]),
    (5, ["Tracked or Nominated for Tracking with Need-Info? Beta " + beta_version + " Bugs", "needinfo_beta", needinfo_beta_url, 0]),

**Comment by anoopvalluthadam** [comment]
@sylvestre I am working on it

**Comment by anoopvalluthadam** [comment]
@sylvestre that last "0" is a Boolean for show_summary; which we are using in root_folder/auto_nag/bugzilla/utils.py:def createQueriesList

So I think it is useful!

Please let me know about your thoughts!

**Comment by jcristau** [comment]
Removed in pull request #84

**Comment by sylvestre** [comment]
thanks
