### ISSUE TITLE
some bugs are listed multiple times in auto-nag email

### ISSUE THREAD

**Issue by dholbert** [mozilla/relman-auto-nag#695]
I received my first "Daily Priority Flag Alert" auto-nag email today, and I noticed that it had a lot of bugs (maybe very bug?) listed multiple times.

Most bugs were listed twice, and many bugs were listed 4 times. Screenshot:
![image](https://user-images.githubusercontent.com/426803/58654228-44c1c680-82cc-11e9-8020-de3c695c188f.png)

**Comment by calixteman** [comment]
For example, for "Layout: Scrolling and Overflow" component, they're 4 people to triage it:
https://gecko.layout.team/triage/layout-overflow.json
