### ISSUE TITLE
Link to buglist from nag e-mail

### ISSUE THREAD

**Issue by svoisen** [mozilla/relman-auto-nag#734]
Minor suggestion for improvement: It would be nice if I could click a link in the auto-nag e-mail to open the list of all bugs in Bugzilla.

**Comment by calixteman** [comment]
Normally it should be there, I'll fix that.

**Comment by calixteman** [comment]
@svoisen it should be fixed now, could you confirm ?

**Comment by svoisen** [comment]
@calixteman Yes, confirmed.
