### ISSUE TITLE
The release management email list should be sorted by Version

### ISSUE THREAD

**Issue by sylvestre** [mozilla/relman-auto-nag#76]
We should have all the issues impacting 45 first, 46 second etc

For now, it is sorted by bug id

**Comment by anoopvalluthadam** [comment]
I will work on it @sylvestre

**Comment by sylvestre** [comment]
@anoopvalluthadam Have you been able to make some progress on this? Thanks

**Comment by anoopvalluthadam** [comment]
Will update you by today evening

On Mon, Apr 25, 2016, 9:57 PM Sylvestre Ledru <notifications@github.com>
wrote:

> @anoopvalluthadam <https://github.com/anoopvalluthadam> Have you been
> able to make some progress on this? Thanks
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly or view it on GitHub
> <https://github.com/mozilla/relman-auto-nag/issues/76#issuecomment-214429596>
>
-- 

~anoop_valluthadam

**Comment by jcristau** [comment]
Pretty sure this is fixed.
