### ISSUE TITLE
Remove `remove_using_history`

### ISSUE THREAD

**Issue by marco-c** [mozilla/relman-auto-nag#775]
The last user is defectenhancementtask.py, but I think we can move that to the Bugzilla query itself (excluding bugs for which the type has ever been changed).

@calixteman agreed?

**Comment by Lothiraldan** [comment]
`remove_using_history` is also used here: https://github.com/mozilla/relman-auto-nag/blob/master/auto_nag/scripts/regression.py#L60

Will try to see if I can move it to Bugzilla query

**Comment by calixteman** [comment]
@marco-c +1
n1: 1,
f1: "bug_type",
o1: "everchanged"

or something similar

**Comment by Lothiraldan** [comment]
@calixteman It's what I used here: https://github.com/Lothiraldan/relman-auto-nag/commit/dacf0b625285ffc876655de87df773bfae0cab4a, I'm guessing that the number, in n1, f1 and o1 is to group the filtering operation together, right?

**Comment by calixteman** [comment]
yep, and n? is for negation
