### ISSUE TITLE
In the report, include bugs that are fixed on Aurora channel but not on Beta.

### ISSUE THREAD

**Issue by rkothari19** [mozilla/relman-auto-nag#81]
In the report, include bugs that are fixed on Aurora channel but not on Beta to catch potential backouts-kind-of-bugs.

**Comment by marco-c** [comment]
The current query is `https://bugzilla.mozilla.org/buglist.cgi?v4=affected&o5=equals&f1=cf_status_firefox" + central_version + "&o3=equals&v3=affected&o1=equals&j2=OR&resolution=---&resolution=FIXED&f4=cf_status_firefox" + beta_version + "&v5=affected&query_format=advanced&f3=cf_status_firefox" + aurora_version + "&f2=OP&o4=equals&f5=cf_status_firefox" + release_version + "&v1=fixed&f7=CP`

I guess we could just add this query: `https://bugzilla.mozilla.org/buglist.cgi?v3=affected&o4=equals&f1=cf_status_firefox" + aurora_version + "&o1=equals&j2=OR&resolution=---&resolution=FIXED&f3=cf_status_firefox" + beta_version + "&v4=affected&query_format=advanced&f2=OP&o3=equals&f4=cf_status_firefox" + release_version + "&v1=fixed&f7=CP` in https://github.com/mozilla/relman-auto-nag/blob/b5cc8a62e53a907c1634d521aa1ece60792395ac/auto_nag/scripts/rm_query_creator.py#L12 and https://github.com/mozilla/relman-auto-nag/blob/b5cc8a62e53a907c1634d521aa1ece60792395ac/auto_nag/scripts/rm_query_creator.py#L18.
And change the first line of the template accordingly: https://github.com/mozilla/relman-auto-nag/blob/b5cc8a62e53a907c1634d521aa1ece60792395ac/templates/tracked_affected_email.

**Comment by marco-c** [comment]
Aurora is dead.
