### ISSUE TITLE
autonag is nagging users who have been removed from a triage calendar

### ISSUE THREAD

**Issue by dblohm7** [mozilla/relman-auto-nag#819]
I used to be a delegate for Core :: General triage, but I am not anymore and I was removed from the calendar. I am still receiving autonag notices as if I were still in the calendar.

**Comment by calixteman** [comment]
Could you forward me the last email you received please ? (cdenizet@mozilla.com)

**Comment by calixteman** [comment]
You're still in the calendar: have a look at the range 2020-02-16 to 2020-02-29.
In the calendar we get (ics file), you're still in it and the rule corresponds to a recurring event every 12 weeks. So I'd say that the changes made in the calendar aren't reflected in the ics we get.
So try to remove the recurring event completely from the calendar.

**Comment by dblohm7** [comment]
I'm receiving these again, so I must have have been scheduled for this week at some point, though my name is no longer present for this week in the calendar. I can confirm that I'm still in that range that you pointed out in 2020. I don't have control over this calendar, but I'll see if I can ask somebody who does.

**Comment by jensstutte** [comment]
I see something similar here: I changed our triage calendar (due to changes in the team), but the mail continues to be sent to the wrong team member (old: ttung, new: asuth, cal: DOM: W&S Triage Rotation). Am I missing something?
