### ISSUE TITLE
In the "Fixed in 52, Affecting 51, 50 or 49" email, we should also include stuff fixed in 51 to be uplifted to 50

### ISSUE THREAD

**Issue by sylvestre** [mozilla/relman-auto-nag#83]
Yesterday, it was merged day.
So, today, the email "Fixed in 52, Affecting 51, 50 or 49" is sent with nightly=52
However, there is a bunch of bugs which are Fixed in 51 but not uplifted to 50. Maybe we want to list them too in the email.

**Comment by marco-c** [comment]
Duplicate of #81.
