### ISSUE TITLE
auto-nag is moving bugs back into components they were moved out of by humans

### ISSUE THREAD

**Issue by gijsk** [mozilla/relman-auto-nag#877]
e.g. https://bugzilla.mozilla.org/show_bug.cgi?id=1580658#c2

There were a few of these today. New Tab Page is definitely not the right place for this bug, so unsure why bugbug is insisting it needs to go there.

**Comment by marco-c** [comment]
It should never happen, https://github.com/mozilla/relman-auto-nag/blob/73ef4f76595ce866a56fc8ee0e5769b7b4b8df1c/auto_nag/scripts/component.py#L46-L54, not sure why it did.

@calixteman any idea?

**Comment by gijsk** [comment]
This just happened a third time, https://bugzilla.mozilla.org/show_bug.cgi?id=1580658#c3 :-\

**Comment by marco-c** [comment]
We'll just disable it until we figure out why the Bugzilla query is no longer working.

**Comment by calixteman** [comment]
It seems to be a bug on Bugzilla's side:
https://bugzilla.mozilla.org/show_bug.cgi?id=1612287

**Comment by marco-c** [comment]
The Bugzilla bug has since been fixed.
