### ISSUE TITLE
Feature Request: If a title or description contains a date, bump a P3+ bug back to triage

### ISSUE THREAD

**Issue by chutten** [mozilla/relman-auto-nag#906]
I occasionally want to file time-delay bugs where I want to do something... but not for a while. Removing expired data collections, removing temporary fixes, changing temporary defaults... that sort of thing. Bugs like https://bugzilla.mozilla.org/show_bug.cgi?id=1617183 

For now it relies on me remembering to file it later, or putting it in my calendar, or filing it and then setting it to P3+, or something.

I would love to be able to file these bugs immediately and for AutoNag to notice them and bump them back out to triage (or needinfo the triage owner) when the date approaches.

(this might not be an appropriate use for autonag. Apologies for the noise if it's not.)

**Comment by calixteman** [comment]
I really like the idea.
Maybe we could add a special keyword in dashboard with a special format to ring a bell when the date is reached, it could be something like: `alarm:YYYY-MM-DD`.
And the when the date is reached, we remove the keyword and make a needinfo on the reporter.
@emceeaich wdyt ?

**Comment by marco-c** [comment]
Something like this is being implemented in #1464.
