### ISSUE TITLE
when a defect is fixed in central but affects beta, ask the assignee about uplift

### ISSUE THREAD

**Issue by jcristau** [mozilla/relman-auto-nag#909]
This is something we currently go through manually based on an email that's sent to release-mgmt, but maybe could be automated: when a bug of type "defect" gets fixed in nightly, but beta is marked as "affected" (maybe also fix-optional?  maybe unset?), ideally we'd like there to be an explicit decision to wontfix or request uplift.

**Comment by jcristau** [comment]
Some refinements that might be worth doing:
- maybe wait a day or three after the bug is fixed in nightly
- don't bother if the bug has known unfixed regressions

**Comment by marco-c** [comment]
Do we have many bugs like these? I'm asking because we likely can't do it if it would cause too much noise for developers.

**Comment by jcristau** [comment]
Looks like 3 bugs right now without doing the refinements, just something like "fixed bugs in nightly affecting beta with no open needinfo and no approval request".

https://bugzilla.mozilla.org/buglist.cgi?list_id=15127275&query_format=advanced&v2=affected&o4=notsubstring&o1=anyexact&f4=flagtypes.name&f1=cf_status_firefox_nightly&resolution=FIXED&v3=defect&v5=needinfo&f5=flagtypes.name&f3=bug_type&o2=equals&v4=approval-mozilla-beta&v1=fixed%2Cverified&o5=notsubstring&o3=equals&f2=cf_status_firefox_beta

**Comment by marco-c** [comment]
I'd say that's a low enough number :)

**Comment by sylvestre** [comment]
+1

**Comment by jcristau** [comment]
To be fair that's in part because we've been going through them manually regularly, but I think the number should stay within reasonable range.

**Comment by calixteman** [comment]
I made a patch:
https://github.com/mozilla/relman-auto-nag/pull/912
I just handled the case where beta is explicitly `affected`.

**Comment by jcristau** [comment]
Seems to be working fine.  Let's use separate issues if/when we need to tweak this.
