### ISSUE TITLE
Bugzilla query for untriaged Core: General bugs should use the Severity field instead of Priority

### ISSUE THREAD

**Issue by ethantseng** [mozilla/relman-auto-nag#959]
From the latest email "[autonag] Bugs to triage for the 2020-05-08" for the Core: General component, the Bugzilla query is still using the **Priority** field to identify untriaged bugs.
We should update the query to use the **Severity** field instead so we comply with the current Firefox Bug Triage Process.

**Comment by emceeaich** [comment]
The fix for that is being worked on in #953.
