### ISSUE TITLE
Severity nag needinfos are happening for already-triaged (pre-Severity-triage switchover) tickets

### ISSUE THREAD

**Issue by dholbert** [mozilla/relman-auto-nag#965]
On Friday of last week (May 15), when I was the layout team's weekly triage rotation, I got a series of relman-auto-nag needinfos for already-triaged bugs which had simply been filed & priority-field-triaged before the switchover to severity-based triage.

I think this was a mistake? (and I'm guessing these might continue to go out, to whoever is on the triage rotation; hence, filing this issue to see if we can avoid bothering folks with further retriage-needinfo-nags)

A few of these:
https://bugzilla.mozilla.org/show_bug.cgi?id=1633410#c18
https://bugzilla.mozilla.org/show_bug.cgi?id=1633254#c14
https://bugzilla.mozilla.org/show_bug.cgi?id=1632028#c8
https://bugzilla.mozilla.org/show_bug.cgi?id=1633254#c14

**Comment by dholbert** [comment]
(see also #964 which is similar but about emails rather than needinfo-pings)

**Comment by emceeaich** [comment]
The queries are similar in terms of time range. See the discussion in https://github.com/mozilla/relman-auto-nag/issues/965 for how to proceed.
