### ISSUE TITLE
Don't nag on S1, S2 bugs without an assignee

### ISSUE THREAD

**Issue by emceeaich** [mozilla/relman-auto-nag#974]
We are sending these nags, but they aren't required.

**Comment by emceeaich** [comment]
@calixteman, I could not find a script or a template sending nags for S1, or S2 bugs without an assignee.

**Comment by calixteman** [comment]
@emceeaich Do you have an example ?
AFAIK the only nag about severity is the one you rewrote: https://github.com/mozilla/relman-auto-nag/blob/master/auto_nag/scripts/workflow/no_severity.py
So maybe, the query should be rewrote to not get the bugs with no assignee.

**Comment by emceeaich** [comment]
We can close this then. I think the source of the requests engineers were mentioning was the REOs asking about S1 and S2 bugs without an assignee!
