### ISSUE TITLE
Identify intermittent bugs with 'intermittent-failure' keyword and not with id of bug reporter

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla/relman-auto-nag#983]
At least [close_intermittents.py](https://github.com/mozilla/relman-auto-nag/blob/master/auto_nag/scripts/close_intermittents.py) identifies intermittent bugs by checking if the bug reporter is `intermittent-bug-filer@mozilla.bugs`. Not every bug reported by this proxy is intermittent (it's treeherder UI has a checkbox to not set the `intermittent-failure` keyword). 

Only bugs with the keyword `intermittent-failure` should be considered for closing.

**Comment by sylvestre** [comment]
@Archaeopteryx we are understaffed on this project. Mostly maintenance mode.
but happy to take a PR.
do you want to give a try?
It should be 3 or 4 hours of work for a beginner with some Python experience.

**Comment by jcristau** [comment]
Otherwise I can probably take this.

**Comment by marco-c** [comment]
Fixed by #984.
