### ISSUE TITLE
Don't nag about no-severity/priority bugs until they've been inactive for 7 days

### ISSUE THREAD

**Issue by gijsk** [mozilla/relman-auto-nag#985]
In https://bugzilla.mozilla.org/show_bug.cgi?id=1645332 I got 3 needinfos in a row, one every day, on a bug that is actively being triaged - but we don't have steps to reproduce (or even full details of what is causing the issue, and if it ends up being an issue with protocol handling, file handling, a webcompat issue, or what) and so I am deliberately not setting severity / priority: without knowing what the actual issue is, there's also no knowing how widespread it is and so how severe it is, plus if it ends up moving components it'll get reset anyway.

The bot shouldn't be continually harassing me to set this if there is activity (comments / product/component being changed / needinfo flags) in the last 7 days. If a bug goes quiet, by all means ping it. But don't interject every day, it's super annoying.

**Comment by emceeaich** [comment]
I looked at the thread on that bug and the needinfo kept getting cleared, which triggered the new needinfos. The best thing would be to either not clear the NI or reassign it. 

If the bug was stalled, which this one was not since it's being researched, it'd be good for use to skip on the stalled keyword.

**Comment by gijsk** [comment]
> I looked at the thread on that bug and the needinfo kept getting cleared, which triggered the new needinfos. The best thing would be to either not clear the NI or reassign it.

My needinfo queue is already a mess, so I'm not enthusiastic about this idea. Also, keeping one needinfo so I don't get a different kind of needinfo feels like it doesn't actually address the problem...
